local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("AuctionProfitMaster", "enUS", true)
if not L then return end

L["Displays the Auction Profit Master log describing what it's currently scanning, posting or cancelling."] = true
L["Enables Auction Profit Master auto mailer, the last patch of mails will take ~10 seconds to send.\n\n[WARNING!] You will not get any confirmation before it starts to send mails, it is your own fault if you mistype your bankers name."] = true
L["Clicking this will post auctions based on the data scanned."] = true
L["Allows you to override the per auction is a cap settings for this group."] = true
L["Override per auction is a cap"] = true
L["Use per auction as cap"] = true
L["If you don't have enough items for a full post, it will post with what you have."] = true
L["%d (max %d) posted by yourself (%s)"] = true
L["%d log messages waiting"] = true
L["%d mail"] = true
L["%s lowest buyout %s (threshold %s), total posted |cfffed000%d|r (%d by you)"] = true
L["/apm cancel <match> - Cancels all auctions that match the entered filter, if you enter glyph it will cancel everything with \"glyph\" in it."] = true
L["/apm cancelall <group/12/2> - Cancels all active auctions, or cancels auctions in a group if you pass one, or cancels auctions with less than 12 or 2 hours left."] = true
L["/apm config - Toggles the configuration"] = true
L["/apm summary - Shows the auction summary"] = true
L["/apm tradeskill - Toggles showing the craft queue window for tradeskills"] = true
L["12 hours"] = true
L["24 hours"] = true
L["48 hours"] = true
L["ALTER_PERFECT"] = true
L["Add a new player to your whitelist."] = true
L["Add group"] = true
L["Add items"] = true
L["No items to send."] = true
L["Add items matching"] = true
L["Add items/groups"] = true
L["Add mail target"] = true
L["Add player"] = true
L["All items that match the entered name will be automatically added to be mailed to %s, \"Glyph of\" will add all glyphs in your inventory for example."] = true
L["Allows you to override bid percent settings for this group."] = true
L["Allows you to override the auto fallback settings for this group."] = true
L["Allows you to override the default cancel settings for this group."] = true
L["Allows you to override the default post time sttings for this group."] = true
L["Allows you to override the default stack ignore settings for this group."] = true
L["Allows you to override the fallback price for this group."] = true
L["Allows you to override the per auction settings for this group."] = true
L["Allows you to override the post cap settings for this group."] = true
L["Allows you to override the price gap settings for this group."] = true
L["Allows you to override the threshold settings for this group."] = true
L["Allows you to override the undercut settings for this group."] = true
L["Are you SURE you want to delete this group?"] = true
L["Auction House closed before you could tell Auction Profit Master to cancel."] = true
L["Auction House must be visible for you to use this."] = true
L["Auction scan finished, can now smart cancel auctions.\n\nScan data age: %d %s"] = true
L["Auction settings"] = true
L["Auto mail"] = true
L["Auto mailed items off to %s!"] = true
L["Auto mailer"] = true
L["Auto mailing will let you setup groups and specific items that should be mailed to another character.\n\nCheck your spelling! If you typo a name it will send it to the wrong person."] = true
L["Auto recheck mail"] = true
L["Automatically rechecks mail every 60 seconds when you have too much mail.\n\nIf you loot all mail with this enabled, it will wait and recheck then keep auto looting."] = true
L["Bid percent"] = true
L["Bracer"] = true
L["Bracers"] = true
L["Buy"] = true
L["Cancel"] = true
L["Cancel auctions with bids"] = true
L["Cancel binding"] = true
L["Canceling"] = true
L["Cancelled %s"] = true
L["Cancelling interrupted due to Auction House being closed."] = true
L["Cancelling |cfffed000%d|r of |cfffed000%d|r"] = true
L["Cancels any posted auctions that you were undercut on."] = true
L["Cannot cancel auctions without the Auction House window open."] = true
L["Cannot find class index. APM still needs to be localized into %s for this feature to work."] = true
L["Cannot find data for %s."] = true
L["Cannot finish auto looting, inventory is full or too many unique items."] = true
L["Click an item or group to add it to the list of items to be automatically mailed to %s."] = true
L["Click an item to add it to this group, you can only have one item in a group at any time."] = true
L["Click an item to remove it from this group."] = true
L["Click to buy materials required.\n\nThis might lock your client up for a few seconds."] = true
L["Click to view Auction Profit Master tradeskill queue"] = true
L["Clicking an item or group will stop Auction Profit Master from auto mailing it to %s."] = true
L["Clicking this will cancel auctions based on the data scanned."] = true
L["Consumable"] = true
L["Could not post all auctions, ran out of space."] = true
L["Craft queue help"] = true
L["Delete"] = true
L["Delete group"] = true
L["Delete this group, this cannot be undone!"] = true
L["Disable auto cancelling"] = true
L["Disable automatically cancelling of items in this group if undercut."] = true
L["Disables cancelling of auctions with a market price below the threshold, also will cancel auctions if you are the only one with that item up and you can relist it for more."] = true
L["Disabling auto mail, SHIFT key was down when opening the mail box."] = true
L["Does a status scan that helps to identify auctions you can buyout to raise the price of a group your managing.\n\nThis will NOT automatically buy items for you, all it tells you is the lowest price and how many are posted."] = true
L["Elemental"] = true
L["Enable auto fallback"] = true
L["Enables Auction Profit Master auto mailer, the last patch of mails will take ~10 seconds to send.\n\nL[WARNING!] You will not get any confirmation before it starts to send mails, it is your own fault if you mistype your bankers name."] = true
L["Enabling groups will cause them to be active and usable in this profile. If you disable them you will no longer see them in the configuration menu, and they will not be managed by Auction Profit Master.|n|nFor all intents and purposes, they do not exist in Auction Profit Master."] = true
L["Enchant materials"] = true
L["Enchant scrolls"] = true
L["Enchanting"] = true
L["Fallback price"] = true
L["Fallbacks"] = true
L["Finished cancelling |cfffed000%d|r auctions"] = true
L["Finished posting |cfffed000%d|r items"] = true
L["Finished status report"] = true
L["Flask"] = true
L["Flasks"] = true
L["Food"] = true
L["Food & Drink"] = true
L["Gem"] = true
L["Gems"] = true
L["General"] = true
L["Get Data"] = true
L["Glyph"] = true
L["Glyphs"] = true
L["Group name"] = true
L["Group named \"%s\" already exists!"] = true
L["Group status"] = true
L["Groups"] = true
L["Help"] = true
L["Herb"] = true
L["Herbs"] = true
L["Hide help text"] = true
L["Hide uncraftables"] = true
L["Hides auction setting help text throughout the group settings options."] = true
L["How long auctions should be up for."] = true
L["How low the market can go before an item should no longer be posted."] = true
L["How many auctions at the lowest price tier can be up at any one time."] = true
L["How many items should be in a single auction, 20 will mean they are posted in stacks of 20."] = true
L["How many seconds until the mailbox will retrieve new data and you can continue looting mail."] = true
L["How much of a difference between auction prices should be allowed before posting at the second highest value.\n\nFor example. If Apple is posting Runed Scarlet Ruby at 50g, Orange posts one at 30g and you post one at 29g, then Oranges expires. If you set price threshold to 30% then it will cancel yours at 29g and post it at 49g next time because the difference in price is 42% and above the allowed threshold."] = true
L["How much to undercut other auctions by, format is in \"#g#s#c\" but can be in any order, \"50g30s\" means 50 gold, 30 silver and so on."] = true
L["If the data is too old and instead of canceling you would rather rescan auctions to get newer data just press this button."] = true
L["If the market price is above fallback price * maximum price, items will be posted at the fallback * maximum price instead.\n\nEffective for posting prices in a sane price range when someone is posting an item at 5000g when it only goes for 100g."] = true
L["Ignore stacks over"] = true
L["Invalid monney format entered, should be \"#g#s#c\", \"25g4s50c\" is 25 gold, 4 silver, 50 copper."] = true
L["Invalid time entered, should either be 12 or 2 you entered \"%s\""] = true
L["Item Enhancement"] = true
L["Item groups"] = true
L["Item list"] = true
L["Items"] = true
L["Items that are stacked beyond the set amount are ignored when calculating the lowest market price."] = true
L["Log"] = true
L["Log (%d)"] = true
L["Management"] = true
L["Mass add"] = true
L["Mass adds all items matching the below, entering \"Glyph of\" will mass add all items starting with \"Glyph of\" to this group."] = true
L["Mass cancelling posted items"] = true
L["Mass cancelling posted items below %s"] = true
L["Mass cancelling posted items in the group |cfffed000%s|r"] = true
L["Mass cancelling posted items with less than %d hours left"] = true
L["Mass mailing"] = true
L["Materials required"] = true
L["Maximum price gap"] = true
L["Maxmimum price"] = true
L["Name of the new group, this can be whatever you want and has no relation to how the group itself functions."] = true
L["New group name"] = true
L["No auctions or inventory items found that are managed by Auction Profit Master that can be scanned."] = true
L["No auctions posted"] = true
L["No group named %s exists."] = true
L["No items have been added to this group yet."] = true
L["No name entered."] = true
L["No player name entered."] = true
L["None posted by yourself"] = true
L["Not all your auctions were posted, ran out of space to split items even after waiting 20 seconds."] = true
L["Nothing to cancel"] = true
L["Nothing to cancel, no matches found for \"%s\""] = true
L["Nothing to cancel, you have no unsold auctions up."] = true
L["Ok"] = true
L["Once market goes below %s/per item, auctions will be automatically posted at the fallback price of %s/per item."] = true
L["Open all"] = true
L["Opening..."] = true
L["Override auto fallback"] = true
L["Override bid percent"] = true
L["Override cancel settings"] = true
L["Override fallback"] = true
L["Override max price"] = true
L["Override per auction"] = true
L["Override post cap"] = true
L["Override post time"] = true
L["Override price gap"] = true
L["Override stack settings"] = true
L["Override threshold"] = true
L["Override undercut"] = true
L["Per auction"] = true
L["Percentage of the buyout as bid, if you set this to 90% then a 100g buyout will have a 90g bid."] = true
L["Perfect (.+)"] = true
L["Player \"%s\" is already a mail target."] = true
L["Player name"] = true
L["Post"] = true
L["Post cap"] = true
L["Post items from your inventory into the auction house."] = true
L["Post time"] = true
L["Posting %s%s (%d) bid %s, buyout %s"] = true
L["Posting %s%s (%d) bid %s, buyout %s (Buyout went below zero, undercut by 1 copper instead)"] = true
L["Posting %s%s (%d) bid %s, buyout %s (Forced to fallback price, lowest price was too high)"] = true
L["Posting %s%s (%d) bid %s, buyout %s (Forced to fallback price, market below threshold)"] = true
L["Posting %s%s (%d) bid %s, buyout %s (Increased bid price due to going below thresold)"] = true
L["Posting %s%s (%d) bid %s, buyout %s (Increased buyout price due to going below thresold)"] = true
L["Posting %s%s (%d) bid %s, buyout %s (No other auctions up)"] = true
L["Posting %s%s (%d) bid %s, buyout %s (Price difference too high, used second lowest price intead)"] = true
L["Posting auctions for |cfffed000%d|r hours, ignoring auctions with more than |cfffed000%d|r items in them, but will not cancel auctions even if undercut."] = true
L["Posting auctions for |cfffed000%d|r hours, ignoring auctions with more than |cfffed000%d|r items in them."] = true
L["Preload groups"] = true
L["Price"] = true
L["Price threshold"] = true
L["Price threshold on %s at %s, second lowest is |cfffed000%d%%|r higher and above the |cfffed000%d%%|r threshold, cancelling"] = true
L["Price to fallback too if there are no other auctions up, the lowest market price is too high."] = true
L["Quantities"] = true
L["Queued %s to be posted"] = true
L["Queued %s to be posted (Cap is |cffff2020%d|r, only can post |cffff2020%d|r need to restock)"] = true
L["Auction Profit Master"] = true
L["Quick binding you can press to cancel auctions once scan has finished.\n\nThis can be any key including space without overwriting your jump key."] = true
L["Read me, important information below!\n\nAs of 3.3 Blizzard requires that you use a hardware event (key press or mouse click) to cancel auctions, currently there is a loophole that allows you to get around this by letting you cancel as many auctions as you need for one hardware event."] = true
L["Remove items"] = true
L["Remove items/groups"] = true
L["Rename"] = true
L["Rename this group to something else!"] = true
L["Rescan"] = true
L["Reset craft queue"] = true
L["Reset the craft queue list for every item."] = true
L["Retry |cfffed000%d|r of |cfffed000%d|r for %s"] = true
L["Scan finished!"] = true
L["Scan interrupted before it could finish"] = true
L["Scan interrupted due to Auction House being closed."] = true
L["Scanned page |cfffed000%d|r of |cfffed000%d|r for %s"] = true
L["Scanning %s"] = true
L["Scanning page |cfffed000%d|r of |cfffed000%d|r for %s"] = true
L["Scanning |cfffed000%d|r items..."] = true
L["Scroll of (.+)"] = true
L["Scroll of Enchant (.+)"] = true
L["Scroll of Enchant (.+) %- .+"] = true
L["Show craft queue"] = true
L["Show uncraftables"] = true
L["Shows information on how to use the craft queue"] = true
L["Simple"] = true
L["Skipped %s lowest buyout is %s threshold is %s"] = true
L["Skipped %s need |cff20ff20%d|r for a single post, have |cffff2020%d|r"] = true
L["Skipped %s posted |cff20ff20%d|r of |cff20ff20%d|r already"] = true
L["Skipped cancelling %s flagged to not be canelled."] = true
L["Skipped cancelling %s flagged to post at fallback when market is below threshold."] = true
L["Slash commands"] = true
L["Smart cancelling"] = true
L["Start"] = true
L["Starting to cancel..."] = true
L["Status"] = true
L["Stop"] = true
L["Stopped splitting due to Auction House frame being closed."] = true
L["Summary"] = true
L["Super scan is enabled, you will not be able to use your whitelist. Disable super scanner to use the whitelist again."] = true
L["The below are fallback settings for groups, if you do not override a setting in a group then it will use the settings below.\n\nWarning! All auction prices are per item, not overall. If you set it to post at a fallback of 1g and you post in stacks of 20 that means the fallback will be 20g."] = true
L["The craft queue in Auction Profit Master is a way of letting you queue up a list of items that can then be seen in that professions Tradeskill window, or through /apm tradeskill with a tradeskill open.\n\n|cffff2020**NOTE**|r This does not work with the enchant scroll category.\nQueues are setup through the summary window by holding SHIFT + double clicking an item in the summary.\n\nFor example: If you want to cut 20 |cff0070ddL[Insightful Earthsiege Diamond]|r you SHIFT + double click the |cff0070ddL[Insightful Earthsiege Diamond]|r text in the summary window, it will then show\n\n|cfffed0000 x|r Insightful Earthsiege Diamond|r\n\nThis tells you that it is ready and you can input how many you want, once you are done setting how many you want to make hit ENTER. If you were to enter 20 it will now look like\n\n0 x |cff20ff202Insightful Earthsiege Diamond|r\nAnd you're done! Once you open the Jewelcrafting Tradeskill window you will see a frame pop up with\n\n|cff0070ddL[Insightful Earthsiege Diamond]|r L[20]\n\nIf you click that text you will create 20 |cff0070ddL[Insightful Earthsiege Diamond]|r providing you have the materials"] = true
L["The player \"%s\" is already on your whitelist."] = true
L["This is a new info panel that will pop up when something changed in Auction Profit Master that you should know, these messages will only show up once.\n\nSettings have been moved around to work better with profiles, groups and all misc smart cancel/etc settings are now global, while per-group settings are per profile.\nYou can change your profile depending on server or how aggressive you want to be without losing your general settings or your group through /AuctionProfitMaster.\n\nBecause of the move in scope, general settings were reset, as well as auto mailing settings. Make sure you reconfigure them!"] = true
L["Toggles hiding items you cannot craft in the summary window."] = true
L["Toggles the craft queue window"] = true
L["Trade Goods"] = true
L["Undercut by"] = true
L["Undercut on %s by |cfffed000%s|r, but %s placed a bid of %s so not cancelling"] = true
L["Undercut on %s by |cfffed000%s|r, buyout %s, yours %s (per item)"] = true
L["Undercut on %s by |cfffed000%s|r, their buyout %s, yours %s (per item), threshold is %s not cancelling"] = true
L["Undercutting auctions by %s/per item until price goes below %s/per item, unless there is greater than a |cfffed000%.2f%%|r price difference between lowest and second lowest in which case undercutting second lowest auction."] = true
L["View a summary of what the highest selling of certain items is."] = true
L["Waiting..."] = true
L["When no auctions are up, or the market price is above %s/per item auctions will be posted at the fallback price of %s/per item."] = true
L["When the market price of an item goes below your threshold settings, it will be posted at the fallback setting instead."] = true
L["Whitelist"] = true
L["Whitelists allow you to set other players besides you and your alts that you do not want to undercut; however, if somebody on your whitelist matches your buyout but lists a lower bid it will still consider them undercutting."] = true
L["Will cancel auctions even if they have a bid on them, you will take an additional gold cost if you cancel an auction with bid."] = true
L["Will post at most |cfffed000%d|r auctions in stacks of |cfffed000%d|r."] = true
L["You are the only one posting %s, the fallback is %s (per item), cancelling so you can relist it for more gold"] = true
L["You did not seem to enter any filters to cancel with. If you really meant to cancel everything, use /apm cancelall"] = true
L["You do not have any items to add to this group, either your inventory is empty or all the items are already in another group."] = true
L["You do not have any items to post"] = true
L["You do not have any players on your whitelist yet."] = true
L["You do not need to add \"%s\", alts are whitelisted automatically."] = true
L["\n\n%d in inventory\n%d on the Auction House"] = true
L["hours"] = true
L["lowest price"] = true
L["minutes"] = true
L["seconds"] = true
L["undercut"] = true
L["Elemental"] = true
L["Elixir"] = true
L["Elixirs"] = true
L["Potion"] = true
L["Potions"] = true