if GetLocale() == "frFR" then


function pslocale()


	pcicccombat4 = "aucune donnée"
	psaddonmy = "Addon"
	psaddonoff = "ARRÊT"
	psaddonofmodno = "Addon désactivé - Ce module n'est pas chargé"
	psaddonok = "OK"
	psaddonon = "Addon activé"
	psaddonon2 = "MARCHE"
	psaddonrepnoprom = "Annonce les alertes sans promotion"
	psaddonrepnoprom2 = "Maintenant vous pouvez annoncer toutes les alertes sans promotion"
	psaddonrepnoprom3 = "Maintenant vous devez être promu pour annoncer les alertes"
	psaddonrepon = "Activer les alertes dans le Tchat"
	psaddonrscafterfigh1 = "|cff00ff00RSC|r > rapporte également qui A UTILISE de pré-pot quand PS rapporte un échec après le combat" -- Needs review
	psaddonrscafterfigh2 = "|cff00ff00RSC|r > rapporte également qui N'A PAS UTILISE de pré-pot quand PS rapporte un échec après le combat" -- Needs review
	psaddonrscafterfigh3 = "|cff00ff00RSC|r > rapporte également qui N'A PAS UTILISE de potion en combat quand PS rapporte un échec après le combat" -- Needs review
	psallinhronic = "toutes les infos dans l'ordre chronologique"
	psannouncebut = "Annoncer dans le canal de guilde" -- Needs review
	psannouncebutdesc = "- active également temporairement la convertion en raid et l'invitation automatique si ils étaient désactivés (Pour macro: |cff00ff00/script ps_inv_ann()|r)" -- Needs review
	psannounceinvtext = "Annoncer l'invitation:" -- Needs review
	psannouncephrase = "Invitation automatique: chuchotez 'inv' pour rejoindre le raid" -- Needs review
	psattack = "ASSAUT !"
	psattackin = "Assaut dans"
	psattention = "Attention!"
	psautoinvmodname = "Invitation automatique" -- Needs review
	psautoinvmodname2 = "Module d'invitation automatique, invite, accepte l'invitation, reconstruit votre raid" -- Needs review
	psautoinvopt1 = "Invite automatiquement les joueurs qui chuchottent une de ces phrases (séparées par des virgules):" -- Needs review
	psautoinvopt2 = "L'invitation automatique fonctionne uniquement avec mes amis et les membres de la guilde" -- Needs review
	psautoinvopt3 = "Convertit le groupe en raid si nous sommes déjà 5 et un joueur supplémentaire veut nous rejoindre" -- Needs review
	psautoinvopt5 = "Accepter automatiquement les invitations de mes amis et des membres de la guilde" -- Needs review
	psautoinvopt6 = "Reconstruire le raid ou le groupe : renvoyer tout le monde et les réinviter automatiquement après 10 secondes" -- Needs review
	psautoinvtxtdef1 = "inv" -- Needs review
	psautoinvtxtdef2 = "inviter" -- Needs review
	psautoinvtxtdef3 = "!inv" -- Needs review
	psautoinvtxtdef4 = "inv moi" -- Needs review
	psautomarktxtinf = "Vous souhaitez marquer les joueurs, mais Boss Mods change vos marques? Utilisez ce module! Il mettra à jour les marques si un autre addon essaye de les changer."
	psautomarnewinfo = "|cff00ff00NEW!|r Maintenant, vous pouvez définir plus d'un surnom pour chaque marque (séparés par des virgules), si le joueur meurt ou se déconnecte - la marque sera mise à jour sur le joueur suivant dans la liste."
	psautomarnotu = "Les marques {rt%s} |cffff0000ne seront PAS|r mise à jour!"
	psautomlset = "- définit automatiquement Maitre du butin sur une personne de la liste (séparés par des virgules, sera défini une fois par session)" -- Needs review
	psautopromotetext1 = "- les promouvoir automatiquement assistants de raid (séparés par des virgules)" -- Needs review
	psbmctitle = "Verification des versions de Boss Mods" -- Needs review
	psbosstr = "Boss" -- Needs review
	psbutbmc = "Vérification des Boss Mods" -- Needs review
	psbutmainopt = "Options Principales"
	psbutmainoptra2 = "Options de raid"
	psbuttonoff = "STOP"
	psbuttonon = "Départ"
	psbuttonreset = "Réinitialisé"
	psbuttonrezallsave = "Réinitialiser toutes les informations" -- Needs review
	psbuttonrezallsave2 = "- réinitialise les informations 'en combat', 'Après combat', 'Dégâts/Switch' et RSC potions s'il est installé" -- Needs review
	pscanceled = "ANNULE!"
	pscast1 = "Incantation" -- Needs review
	pschataddbut = "Ajouter"
	pschataddfail = "Il n'y a pas de canaux à ajouter"
	pschataddsuc = "a été ajouté avec succès"
	pschataddtxtset1 = "Choisissez dans le menu ci dessous le canal de discussion que vous souhaitez  |cff00ff00ajouter|r dans la liste"
	pschataddtxtset2 = "Il n'y a aucun canal disponible à ajouter, essayez de le rejoindre : /join nom_du_canal."
	pschatchopt = "Options des canaux de discussions"
	pschatlist1 = "raid"
	pschatlist2 = "alerte raid"
	pschatlist3 = "officier"
	pschatlist4 = "groupe"
	pschatlist5 = "guilde"
	pschatlist6 = "dit"
	pschatlist7 = "cri"
	pschatlist8 = "soi même"
	pschatmaxchan = "Vous ne pouvez ajouter plus de 5 canaux personnel"
	pschatnothadd = "Pas disponible sur ce canal"
	pschatopttitl = "Canaux de discussion : ajouter/supprimer"
	pschatrembut = "Supprimer"
	pschatremfail = "Les canaux par défaut ne peuvent être supprimés"
	pschatremsuc = "a été supprimé avec succès"
	pschattitl2 = "Par défaut vous avez 8 canaux pour annoncer les informations, ici vous pouvez ajouter et supprimer des canaux personnel puis les choisir pour annoncer les informations dont vous avez besoin."
	pscheckmodenabl = "Vérifier que ce module est activé dans Addons avant de rentrer dans le jeu." -- Needs review
	pschetremtxt1 = "Choisissez dans le menu ci dessous le canal de discussion que vous voulez |cffff0000enlever|r de la liste (les canaux par défaut ne peuvent être supprimé)."
	pscolcast11 = "incante"
	pscolnewveranonce1 = "Le module a bien été mis à jour"
	pscolshieldannonce = "dans la fenêtre de discussion"
	psdamagetr = "dégât" -- Needs review
	psdidfriendlyf = "A fait des dégâts collatéraux" -- Needs review
	psdied = "est mort" -- Needs review
	psdiffsettext = "- définit automatiquement la difficulté après la convertion automatique en raid" -- Needs review
	psdisbandmess = "Dissolution de ce raid/groupe, toute le monde sera réinvité dans 10 secondes" -- Needs review
	psdisbantinvbut = "Dissoudre & Réinviter" -- Needs review
	psdispandquestion = "Voulez-vous vraiment dissoudre et réinviter ce groupe ?" -- Needs review
	psdispellinfo = "Dissipation" -- Needs review
	psdragslastmoduleloadtxt = "Âme des Dragons" -- Needs review
	pserror = "Erreur!"
	pserrorcantdo1 = "Impossible à faire! Tous les addons ont été désactivés, réactivez les et essayez à nouveau"
	pserrorcantdoanotherpullis = "Le pull-timer est déjà lancé par un autre addon !"
	pserrormenutimer1 = "Pour démarrer le Pull-timer, entrez une durée entre 2 et 20 sec."
	pserrormenutimer2 = "exemple : /ps pull 5, pour arrêter le pull-timer entrez /ps pull"
	pserrornotofficer = "Vous n'avez pas la permission d'utiliser cette fonction en raid. Demandez une promotion au Chef du Raid."
	pserroronloadindmoddmgshow = "Ne peut pas charger le module montrant les informations du combat choisi"
	pseventsincomb2 = "informations d'incantations" -- Needs review
	psfneedrscaddon = "Pour ouvrir ce module vous devez installer l'addon 'RaidSlackCheck' "
	psfneedrscaddon2 = "L'addon montre qui utilise des potions en raid et signale qui n'en prend pas"
	psfneedrscaddonver11 = "Version 1.1 ou supérieur"
	psfnotofficerspam = "Vous n'avez aucun droit d'envoyer des alertes, mais elles sont activées dans l'addon"
	psfpotchecklocal = "Vérification des potions"
	psfpotchecklocal2 = "Vérification des potions"
	psfpotchecklocalt2 = "Vérification des Flacons"
	psfpotchecklocalt3 = "Renaissance - Rebuff"
	psfserver = "ru-Gordunni"
	psguildinvnam = "Invitaion de guilde:" -- Needs review
	psiccall = "tous"
	psiccchat1 = "|cff00ff001 canal de discussion pour le msg.:|r"
	psiccchat2 = "|cffff00002 canal de discussion pour le msg.:|r"
	psiccchat3 = "|CFFFFFF003 canal de chat pour msg.:|r"
	psiccdmgfrom = "Dégât de"
	psiccdmgfrom2 = "Pas de dégâts périodiques de"
	psiccheroic = "Héroïque"
	psiccinfoabsv = "Info à propos de:"
	psiccnorezetincombat = "Impossible de remettre à zéro pendant un combat"
	psiccnormal = "normal" -- Needs review
	psiccrezcompl = "Toutes les modifications dans \"% s\" emplacement ont été remises à zéro."
	psiccrezonemore = "Cliquez sur le bouton reset une fois de plus, si vous souhaitez réinitialiser les options!"
	psicctxtbysaved = "Quantité de combats enregistrés:"
	psicctxtkill = "(tuer)"
	psicctxttry = "(essayer)"
	psiccunknown = "inconnu"
	psiccwhispertxt = "chuchote:"
	psiccwhispertxt2 = "dans le chat:"
	psignorsystemmessage1 = "pour rejoindre votre groupe" -- Needs review
	psincombaddtxtlocal1 = "Tout:"
	psincombaddtxtlocal2 = "Uniquement de |cff00ff00%s|r à |cff00ff00%s|r:"
	psincombaddtxtlocal3 = "sélectionnez les lignes pour un rapport partiel:"
	psincombaddtxtlocal4 = "de :"
	psincombaddtxtlocal5 = "vers :"
	psinfo = "info"
	psinterrupted1 = "Interruption"
	psinterrupted2 = "Cast" -- Needs review
	psinterrupted3 = "Interruption: par précast" -- Needs review
	psinterrupted4 = "Interruption: inconnu" -- Needs review
	psinterrupted5 = "Pas interrompu" -- Needs review
	psinterrupted6 = "Interrompu" -- Needs review
	psinviteaccepted = "Invitation de groupage de |cffFFC354%s|r acceptée" -- Needs review
	psinvitebut = "Inviter" -- Needs review
	psinvitebut2 = "inviter ce rang et supérieur" -- Needs review
	psinvtxtwaitforacc = "%s ont été invités, les autres membres seront invités après convertion en gropupe de raid. En attente..." -- Needs review
	psleftmenu2 = "Actualiser automatiquement les signes"
	psleftmenu3 = "Chronos"
	psloadmodulebuttxt = "Charger le module"
	psmain_sa_phrase1 = "sur MOI !"
	psmain_sadenfifenabl1 = "module est désactivé"
	psmain_sadenfifenabl2 = "envoie des phases en dire/crie en utilisant les addons SA" -- Needs review
	psmain_sadescript = "Comment ça marche: Chaque raider doit installer l'addon |cff00ff00SayAnnouncer|r , qui ne nécessite pas dêtre mis à jour, vous pouvez régler les boss ou il y a besoin d'une phrase 'quelquechose sur moi!' dite par les raiders. Très facile à utiliser. Vous pouvez obtenir plus d'informations sur |cff00ff00www.phoenixstyle.com|r" -- Needs review
	psmain_sainfo1 = "Addon installé"
	psmain_sainfo2 = "Addon INTROUVABLE"
	psmain_sainfo3 = "Pas vérifié"
	psmain_saneedpromote = ">>pas suffisamment de droits !<<"
	psmain_saonoff = "|cff00ff00MARCHE|r / |cffff0000ARRET|r" -- Needs review
	psmain_sapaneltitle = "\009    SayAnnouncer - panneau de contrôle"
	psmain_sawait = "attendre 5 sec"
	psmainbattlegr1 = "Vallée d'Alterac"
	psmainbattlegr2 = "Bassin Arathi"
	psmainbattlegr3 = "L'Œil du cyclone"
	psmainbattlegr4 = "Île des Conquérants"
	psmainbattlegr5 = "Rivage des Anciens"
	psmainbattlegr6 = "La bataille de Gilnéas"
	psmainbattlegr7 = "Pics-Jumeaux"
	psmainbattlegr8 = "Goulet des Chanteguerres"
	psmainbgbm = "En champ de bataille" -- Needs review
	psmainbmnotmorethenof = "Vous pouvez envoyer des chuchotements 1 fois toutes les 20s. Attendez un peu" -- Needs review
	psmainbossmsort = "Trié par" -- Needs review
	psmainbossmsort1 = "boss mod" -- Needs review
	psmainbossmsort2 = "nom" -- Needs review
	psmainbossmsort3 = "classe" -- Needs review
	psmaincheckversions = "Vérifier qui n'a pas installé l'addon SA en raid"
	psmaincheckversions2 = "Vérifier les versions"
	psmainfonttxtbut = "Changer la taille des caractères"
	psmainfonttxtdescr = "Une petite taille de caractère dans certains des modules? Vous pouvez changer la taille ici! Certaines polices ne seront changées que |cff00ff00après relog.|r Si votre problème n'est pas résolu - décrivez le dans les commentaires sur un site."
	psmainfonttxttitle = "Modifier la taille de caractère, cet addon utilise"
	psmainfontused1 = "Le texte est trouvé dans les Raids (liste d'options), l'addon RaidAchievement (liste d'options), RSC (liste des options). Par défaut:%s, maintenant:%s"
	psmainfontused2 = "Le texte est trouvé dans PhoenixStyle (descriptions du module, informations de raids sauvegardé), l'addon RaidAchievement (Liste des Hauts-faits, tactiques), RSC (descriptions du module, liste des noms). Par défaut: %s, maintenant: %s"
	psmainmarkgetm = "Récupérer les joueurs marqués d'un symbole dans le raid et les ajouter à la liste:" -- Needs review
	psmainmarkgetm2 = "Récupérer les joueurs marqués d'un symbole" -- Needs review
	psmainmdamagefrom = "Dégâts de" -- Needs review
	psmainmdiedfrom = "est mort par" -- Needs review
	psmainmgot = "A reçu" -- Needs review
	psmainmgotinf = "est allé dans" -- Needs review
	psmainmgotinm = "est allé dans" -- Needs review
	psmainmgotm = "a reçu" -- Needs review
	psmainmhealedhimself = "a soigné" -- Needs review
	psmainmtotal = "total" -- Needs review
	psmainmwhogot = "Qui a reçu" -- Needs review
	psmainnobosm = "Pas de Boss Mod trouvé" -- Needs review
	psmainnotcheckbosm = "Hors ligne (non vérifié)" -- Needs review
	psmainoffline = "Hors-ligne" -- Needs review
	psmainonly = "seulement" -- Needs review
	psmainopttitle = "    Options principales de l'addon"
	psmainraidopttxt1 = "Options pour les informations de raid"
	psmainraidopttxt10 = "Montrer dans tous les messages"
	psmainraidopttxt11 = "Ne pas montrer du tout"
	psmainraidopttxt2 = "Options"
	psmaindeathrepforppl = "pour %s personnes"
	psmainraidopttxt5 = "Le nombre de mort pour considérer le combat actuel comme un |cff00ff00wipe|r et annoncer l'info 'après combat' (vous pouvez également utiliser la commande -|cff00ff00/ps wipe|r):" -- Needs review
	psmainraidopttxt6 = "Le nombre maximum de noms à |cff00ff00envoyer dans la discussion|r après combat"
	psmainraidopttxt7 = "Le nombre maximum de noms à |cff00ff00enregistrer dans l'info 'Après combat'|r:"
	psmainraidopttxt8 = "Symbole {cross} dans le rapport 'après combat:" -- Needs review
	psmainraidopttxt9 = "Montrer seulement dans le premier message"
	psmainraidopttxtmodel = "montrer les modèles des boss dans 'Options pour les raids Cataclysme' " -- Needs review
	psmainrepinf = "envoyer un chuchotement aux raiders qui ont une vieille version de Boss Mod" -- Needs review
	psmainrepinf2 = "envoyer un chuchotement aux raiders qui n'ont pas %s, ou en ont une ancienne version" -- Needs review
	psmainreportoldbm1 = "Vous avez une ancienne version de %s. Votre version est: %s, la dernière en date est: %s" -- Needs review
	psmainreportoldbm2 = "Le vérificateur de Boss Mod n'a trouvé aucun boss mod" -- Needs review
	psmainreportoldbm3 = "le raid a été inspecté pour l'installation de %s. Vous n'avez pas cet addon" -- Needs review
	psmainsadescript = "Choisissez le canal pour cet addon" -- Needs review
	psmainsamodadd = "si désactivé - vous continuez le contrôle des phrases du raid, mais vous n'envoyez pas vos propres phrases dans la discution" -- Needs review
	psmaintooearlybm = "Pour des résultats précis, vous devriez rester dans le raid pour au moins quelques minutes, tous les Boss Mods n'envoient pas instantanément les données sur leur version" -- Needs review
	psmarkinfo1 = "A quelle fréquence mettre les marques à jour, sec.:"
	psmarkinfo2 = "Mettre à jour les marques pour:"
	psmarkinfo3 = "La mise à jour automatique des marques est activé"
	psmarkinfo4 = "Mise à jour automatique des symboles est désactivé"
	psmarkofftxt = "Enlever tous les symboles"
	psmarkreflesh = "Mise à jour automatique des symboles"
	psmarkrefleshoff = "désactivé"
	psmarkrefleshon = "activé"
	psmarks = "Mise à jour automatique des symboles sur les membres du raid"
	psmarkserror = "Vous n'avez pas les droits d'utiliser les symboles sur le raid, mais le module 'Mise à jour automatique des symboles' est actif!"
	psmenuchangtx1 = "Choisir le raid:"
	psmenuchangtx2 = "Choisir le Boss:"
	psmin = "min."
	psminibuttset = "Voir le bouton de la minimap"
	psminut = "min."
	psmob1 = "mob"
	psmoduleload = "Module chargé:"
	psmodulenotload = "Erreur en chargeant le module:"
	psmoduletxtoff = "le module est désactivé"
	psmoduletxton = "le module est activé"
	psnewversfound = "Attention! Une nouvelle version de PhoenixStyle a été trouvée dans votre raid/guilde:"
	psnewversfound2 = "Attention! Une nouvelle version de PhoenixStyle a été trouvée dans votre raid/guilde, votre version est très ancienne, il est fortement recommandé de faire la mise à jour depuis www.ps-addon.com"
	psnofirstsec = "pas les premières %s secondes" -- Needs review
	psnonickset = "Vous n'avez pas entrez de nom."
	psnopermissmark = "Vous n'avez pas de permission pour utiliser les marques dans un raid."
	psnotfoundinr = "non trouvé dans votre raid."
	psnotinraid = "Vous devez être dans un raid!"
	psoldvertxt = "(ancienne version)"
	psonlybossfigtloc = "Seulement les combats contre les boss"
	psoptiontypeofreport1 = "Durant le combat"
	psoptiontypeofreport2 = "Après le combat"
	psoptiontypeofreport3 = "Report des dégâts"
	psoptiontypeofreport4 = "Autre"
	psoverkill = "O" -- Needs review
	pspartreploc = "Extrait de l'information"
	psperc = "pourcent" -- Needs review
	pspereriv = "Pause"
	pspereriv2 = "Pause"
	psraaddonanet = "Erreur! L'addon 'RaidAchievement' n'est pas installé"
	psraaddonanet2 = "Vous pouvez le télécharger sur www.ps-addon.com"
	psraidstxt2 = "Options pour les raids Cataclysm"
	psrankandhigher = "et supérieur" -- Needs review
	psreportingmanylines = "Vous essayez de rapporter plus de 10 lignes (|cffff0000%s|r). Cliquez une fois de plus pour continuer" -- Needs review
	psrscoldvers = "Vous avez une ancienne version de 'RaidSlackCheck'. Il est conseillé de la mettre à jour."
	psrunbutton = "Course"
	pssec = "sec."
	pssecund = "sec."
	pssend = "Envoyé(e)"
	psspaminvgi = "Spam la phrase avant de commencer l'invitaion automatique, l'invitaiton sera différée de 10 secondes" -- Needs review
	psspaminvgiphrase = "Tous les personnages du rang %s seront invités dans 10 secondes. Merci de quitter vos groupes." -- Needs review
	psspellidt1 = "Trouver en utilisant l'ID du sort:"
	psspellidt2 = "Trouver en utilisant le nom du sort ou une partie:"
	psspellidt3 = "Non trouvé"
	psspellidt4 = "Correspondance exacte"
	psspellidt5 = "Correspondance partielle"
	psspellidt6 = "Trop de sorts ont été trouvés (|cffff0000%s|r)! Spécifiez un nom plus précis"
	psspellidt7 = "ou entrer la portée de l'ID à vérifier (>80000 pour les raids Cataclysme)"
	psspelllinkbut = "Récupérer le lien du sort"
	psspelllinkbuttitle = "    Récupérer le lien du sort par son ID ou son nom"
	psstacks = "empilements" -- Needs review
	pssummon = "Invoque" -- Needs review
	psthreshold1 = "Inhabituel" -- Needs review
	psthreshold2 = "Rare" -- Needs review
	psthreshold3 = "Epique" -- Needs review
	psthreshold4 = "Légendaire" -- Needs review
	psthreshold5 = "Artéfact" -- Needs review
	psthresholddesc = "- définit la qualité du butin automatiquement après la convertion automatique en raid" -- Needs review
	psthresholdno = "Par défaut" -- Needs review
	pstimeerror1 = "Entrez un nombre entre 2 et 20 sec."
	pstimeerror2 = "Le temps de pause ne peut pas dépasser 30 min!"
	pstimeerror3 = "Le chrono de pause ne peut pas être inférieur à 30 sec!"
	pstimeerror4 = "Le chrono ne peut pas dépasser 2 heures!"
	pstimeerror5 = "Un chrono ne peut pas être inférieur à 10 sec!"
	pstimerbutton1 = "Démarrer le chrono de pull"
	pstimerbutton2 = "Démarrer le chrono de pause"
	pstimerbutton3 = "Démarrer votre chrono perso"
	pstimernoname = "Non nommé"
	pstimers = "Chrono"
	pstimersinfo1 = "Lorsque vous démarrez un chrono, l'addon démarre un chrono global dans les BossMods pour tous les membres du raid."
	pstimersinfo10 = "ou : /ps attack 5 (n'importe quel nombre entre 2 et 20 sec.)"
	pstimersinfo11 = "ou: entrer secondes pour le chrono d'avant 'Pull':"
	pstimersinfo12 = "Pour mettre en |cffffffffPause|r le timer : |cff00ff00/ps break 10|r"
	pstimersinfo13 = "entrer une durée pour le chrono de 'Pause':"
	pstimersinfo14 = "Créer votre propre chrono"
	pstimersinfo15 = "entrez un nom:"
	pstimersinfo16 = "durée : "
	pstimersinfo2 = "BossMods disponibles:"
	pstimersinfo9 = "Pour le timer 'Pull' utilisez: /ps pull 5"
	pstimerstarts = "Le chrono a commencé"
	pstooclosepl = "Joueurs trop proches (jusqu'à %s m):" -- Needs review
	pstwobm = "L'expiration du chrono sera affichée par les chrono de BigWigs, DBM, DXE et RaidWatch2."
	psuierror = "Erreur !"
	psuierroraddonoff = "Erreur ! L'addon est désactivé - ce module n'a pas été chargé !"
	psuinomodule1 = "Erreur! Le module n'est pas installé!"
	psuinomodule2 = "Erreur! Le module que vous avez choisis n'est pas installé!"
	psulchatch = "Canal de discussion:"
	psulhp = "PV"
	psulsendto = "Envoyer au canal:"
	psulvkl = "sur:"
	pswarnings = "annoncer les avertissements"
	pswarningsoff = "désactivé"
	pswarningson = "activé"
	pswho = "Qui" -- Needs review
	pswhodidff = "Qui a fait des dégâts collatéraux" -- Needs review
	pswhousehstext = "Pierre d'âmes utilisées" -- Needs review
	pswhousehstext2 = "Pierres d'âmes NON utilisées" -- Needs review
	rscloccolor = "noms en couleurs"
	rsclocpot10 = "Qui utilisa"
	rsclocpot11 = "Qui n'utilisa pas"
	rsclocpot2 = "0 potion sélectionnée"
	rsclocrlslak = "Reporter au RL les erreurs"
	saonoff = "|cff00ff00ON|r / |cffff0000OFF|r - si vous n'avez pas les droits suffisants vous annoncerez seulement vos évènements dont les modules sont activés" -- Needs review
	saonoff2 = "si désactivé - vous continuez le contrôle des phrases de raid, mais vous n'envoyez pas vos propres phrases dans la discution" -- Needs review



end

end