if( GetLocale() ~= "ruRU" ) then return end
local L = {}
L[ [=[

%d in inventory
%d on the Auction House]=] ] = [=[%d  в инвентаре
%d на аукционе]=]
L["%d (max %d) posted by yourself (%s)"] = "%d ( максимальное количество %d) выставленное вами ( %s)"
L["%d log messages waiting"] = "%d сообщений лога ожидают"
L["%d mail"] = "%d почта"
L["%s lowest buyout %s (threshold %s), total posted |cfffed000%d|r (%d by you)"] = "%s минимальная цена выкупа %s ( порог %s), всего выставлено |cfffed000%d|r (%d вами)"
L["/qa config - Toggles the configuration"] = " /qa config  - Включает конфигурацию"
L["/qa summary - Shows the auction summary"] = "/qu summary - Резюмирует информацию аукциона"
L["/qa tradeskill - Toggles showing the craft queue window for tradeskills"] = "/qa tradeskill - Включает окно с очередью в профессии для создания предметов "
L["12 hours"] = "12 часов"
L["24 hours"] = "24 часа"
L["48 hours"] = "48 часов" -- Needs review
L["Add a new player to your whitelist."] = "Добавить нового игрока в белый список" -- Needs review
L["Add group"] = "Добавить группу" -- Needs review
L["Add items"] = "Добавить предметы" -- Needs review
L["Add items/groups"] = "Добавить предметы/группы" -- Needs review
L["Add mail target"] = "Добавить получателя" -- Needs review
L["Add player"] = "Добавить игрока" -- Needs review
L["Allows you to override bid percent settings for this group."] = "Позволяет переписывать процент ставки для этой группы" -- Needs review
L["Allows you to override the threshold settings for this group."] = "Позволяет переписать настройки порога для этой группы" -- Needs review
L["Allows you to override the undercut settings for this group."] = "Позволяет переписать настройки по сбиванию цен для этой группы" -- Needs review
L["Are you SURE you want to delete this group?"] = "Вы уверены что хотите удалить эту группу?" -- Needs review
L["Auction House must be visible for you to use this."] = "Откройте аукцион чтобы выполнить это действие" -- Needs review
L["Auction settings"] = "Настройки аукциона"
L["Auctions ready to post."] = "Аукционы готовы к отправке" -- Needs review
L["Auto mail"] = "Автоматическая пересылка" -- Needs review
L["Auto mailed items off to %s!"] = "предметы были автоматически отправлены %s!" -- Needs review
L["Auto mailer"] = "инструмент для автоматической пересылки" -- Needs review
L["Click to view Quick Auctions tradeskill queue"] = "Нажмите чтобы увидеть очередь для ремесла в  Quick Auctions" -- Needs review
L["Clicking this will cancel an auction."] = "При нажатии кнопки аукцион будет отменен"
L["Clicking this will post the auctions."] = "При нажатии кнопки аукционы будут выставлены"
L["Consumable"] = "Расходуемые" -- Needs review
L["Craft queue help"] = "Помощь по создания очереди для ремесла" -- Needs review
L["Elemental"] = "Стихийный" -- Needs review
L["Elixir"] = "Эликсир" -- Needs review
L["Elixirs"] = "Эликсиры" -- Needs review
L["Enchant materials"] = "Материалы для наложения чар" -- Needs review
L["Enchant scrolls"] = "Свитки для наложения чар" -- Needs review
L["Enchanting"] = "Наложение чар" -- Needs review
L["Flask"] = "Настой" -- Needs review
L["Flasks"] = "Настои" -- Needs review
L["Food"] = "Еда" -- Needs review
L["Groups"] = "Группы"
L["Help"] = "Помощь"
L["Herb"] = "Трава"
L["Herbs"] = "Травы"
L["Hide help text"] = "Убрать текст помощи"
L["Hide uncraftables"] = "Спрятать предметы, которые пока невозможно создать"
L["How long auctions should be up for."] = "Сколько должны длиться аукционы" -- Needs review
L["How low the market can go before an item should no longer be posted."] = "Какой допустимый нижний ценовой предел прежде чем лоты перестанут выставляться" -- Needs review
L["Nothing to cancel, you have no unsold auctions up."] = "Нечего отменять, у вас нет непроданных аукционов" -- Needs review
L["Ok"] = "Ок" -- Needs review
L["Open all"] = "Открыть все" -- Needs review
L["Opening..."] = "Открытие..." -- Needs review
L["Posting"] = "В процессе выставления" -- Needs review
L["Posting %s x %d (%d times)"] = "Выставление X раз" -- Needs review
L["Quantities"] = "Количества" -- Needs review
L["Quick Auctions"] = "Quick Auctions  - dont think it needs to be translated" -- Needs review
L["Ready to cancel an auction, press \"Cancel\"."] = "Подготовка к отмене завершена, нажмите \" Отменить\"" -- Needs review
L["Remove items"] = "Убрать предметы" -- Needs review
L["Remove items/groups"] = "Убрать предметы/группы" -- Needs review
L["The player \"%s\" is already on your whitelist."] = "Игрок %S уже находится в Вашем белом списке" -- Needs review
L["Toggles the craft queue window"] = "Открывает окно очереди  для ремесла" -- Needs review
L["Waiting..."] = "Ожидание..." -- Needs review
L["Whitelist"] = "Белый список" -- Needs review

local QuickAuctions = select(2, ...)
QuickAuctions.L = setmetatable(L, {__index = QuickAuctions.L})
