PREFORM_AV_ENABLER_SELF = "Preform AV Enabler";
PREFORM_AV_ENABLER_PREFORM = "Preform";
PREFORM_AV_ENABLER_CMD = "/preformav";

PREFORM_AV_ENABLER_AV = "Alterac Valley";
PREFORM_AV_ENABLER_WSG = "Warsong Gulch";
PREFORM_AV_ENABLER_AB = "Arathi Basin";
PREFORM_AV_ENABLER_EYE = "Eye of the Storm";
PREFORM_AV_ENABLER_STRAND = "Strand of the Ancients";
PREFORM_AV_ENABLER_ISLE = "Isle of Conquest";
PREFORM_AV_ENABLER_TWIN = "Twin Peaks";
PREFORM_AV_ENABLER_GILNEAS = "The Battle for Gilneas";
PREFORM_AV_ENABLER_SILVER = "Silvershard Mines";
PREFORM_AV_ENABLER_TEMPLE = "Temple of Kotmogu";

PREFORM_AV_ENABLER_RANDOM_ABR = "Rnd";
PREFORM_AV_ENABLER_AV_ABR = "AV";
PREFORM_AV_ENABLER_WSG_ABR = "WSG";
PREFORM_AV_ENABLER_AB_ABR = "AB";
PREFORM_AV_ENABLER_EYE_ABR = "Eye";
PREFORM_AV_ENABLER_STRAND_ABR = "SotA";
PREFORM_AV_ENABLER_ISLE_ABR = "IoC";
PREFORM_AV_ENABLER_TWIN_ABR = "Twin";
PREFORM_AV_ENABLER_GILNEAS_ABR = "Gil";
PREFORM_AV_ENABLER_SILVER_ABR = "Silv";
PREFORM_AV_ENABLER_TEMPLE_ABR = "Tmpl";

PREFORM_AV_ENABLER_DESERTER = "Deserter";
PREFORM_AV_ENABLER_QUEUED = "Queued";
PREFORM_AV_ENABLER_CONFIRM = "Confirm";
PREFORM_AV_ENABLER_INSIDE = "Inside";
PREFORM_AV_ENABLER_FIRSTAVAIL = "First Avail";
PREFORM_AV_ENABLER_OPEN = "Open";
PREFORM_AV_ENABLER_CLOSED = "Closed";
PREFORM_AV_ENABLER_WINDOW = "BM";
PREFORM_AV_ENABLER_VER = "Ver";
PREFORM_AV_ENABLER_NUM_INSTANCES = "Instances Running";
PREFORM_AV_ENABLER_INFO = "Info";

PREFORM_AV_ENABLER_NOTINSTALLED = "Status Unknown/Not Installed";
PREFORM_AV_ENABLER_ATTEMPT = "Attempting to Join ";
PREFORM_AV_ENABLER_INSTANCE = "Instance ID ";
PREFORM_AV_ENABLER_NOTFOUND = " not found.  Re-open battlefield selection window quickly to queue!";
PREFORM_AV_ENABLER_WAKE_UP = "Open the %s battlemaster window";
PREFORM_AV_ENABLER_JOIN_THIS = "Your raid leader wants you to join \n\n|cff20ff20%s|r\n";
PREFORM_AV_ENABLER_LEAVE_THIS = "Your raid leader wants you to leave the queue\n\n%s";

PREFORM_AV_ENABLER_GROUPLEAVE = "Group Leave";
PREFORM_AV_ENABLER_STATUSCHECK = "Status Check";
PREFORM_AV_ENABLER_QUEUE = "Queue";
PREFORM_AV_ENABLER_AUTOMATE = "Automate";
PREFORM_AV_ENABLER_THRESHOLD = "Threshold";
PREFORM_AV_ENABLER_LEAVEALL = "Leave All";
PREFORM_AV_ENABLER_NOTIFY = "Notify";
PREFORM_AV_ENABLER_BUTTONIZE = "Buttonize";
PREFORM_AV_ENABLER_FORCED_JOIN = "Leader Forced Join";

PREFORM_AV_ENABLER_TOOLTIP0 = "Click this if you believe the status window to be inaccurate";
PREFORM_AV_ENABLER_TOOLTIP1 = "Force every group member to solo queue this battleground";
PREFORM_AV_ENABLER_TOOLTIP2 = "Send the signal to join the battleground";
PREFORM_AV_ENABLER_TOOLTIP3 = "Leave the queue (if you are in it)";
PREFORM_AV_ENABLER_TOOLTIP4 = "Force everybody with the addon installed to leave their queues for this BG";
PREFORM_AV_ENABLER_TOOLTIP5 = "Automatically queue the raid when everybody is ready, and send a join signal when threshold number of members have confirms";
PREFORM_AV_ENABLER_TOOLTIP6 = "The number of confirms before Automate sends the single to join";
PREFORM_AV_ENABLER_TOOLTIP7 = "Force everybody with this addon installed to leave any and all battleground queues they may have, not just AV";
PREFORM_AV_ENABLER_TOOLTIP8 = "Notify the raid members who do not have the battlemaster window you have open to open it";
PREFORM_AV_ENABLER_TOOLTIP9 = "Create unit buttons for raid members.  If checked, you will not be able to resize, open, or close the Preform AV Enabler frame while in combat.  Checking this off requires a UI reload to take effect";
PREFORM_AV_ENABLER_TOOLTIP10 = "Allow the raid leader to control your joining of battlegrounds";
PREFORM_AV_ENABLER_TOOLTIP11 = "Enter '"..PREFORM_AV_ENABLER_CMD.." ?' at the command line for more options";
