local L = LibStub("AceLocale-3.0"):NewLocale("PitBull4", "ptBR")
if not L then return end

--@non-debug@
L["10-man raid"] = "Raide 10-homens" -- Needs review
-- L["15-man raid"] = ""
-- L["20-man raid"] = ""
L["25-man raid"] = "Raide 25-homens" -- Needs review
L["2D"] = "2D" -- Needs review
L["3D"] = "3D" -- Needs review
L["3D question mark"] = "Marca de interrogação 3D" -- Needs review
L["40-man raid"] = "Raide 40-homens" -- Needs review
-- L["5-man raid"] = ""
L["Above"] = "Acima" -- Needs review
L["Above-left"] = "Esquerda acima" -- Needs review
L["Above-right"] = "Direita acima" -- Needs review
L["Absolute"] = "Absoluto" -- Needs review
L["Absolute and percent"] = "Absoluto e porcentagem"
L["Absolute short"] = "Curto absoluto"
-- L["Active color"] = ""
-- L["Add a enemy debuff to the extra enemy debuff filter."] = ""
-- L["Add a friend buff to the extra friend buff filter."] = ""
-- L["Add a friend debuff to the extra friend debuff filter."] = ""
-- L["Add a friend debuff to the extra friend debuff highlights."] = ""
-- L["Add aggro coloring to the unit frame."] = ""
-- L["Add an enemy buff to the extra enemy buff highlights."] = ""
L["Add a new event to LuaTexts."] = "Adicione um nova evento aos textos Lua." -- Needs review
-- L["Add a new name to the list."] = ""
-- L["Add an id to the list."] = ""
-- L["Add enemy debuff"] = ""
-- L["Add enemy highlight"] = ""
-- L["Add friend buff"] = ""
-- L["Add friend debuff"] = ""
-- L["Add friend highlight"] = ""
-- L["Add or remove auras by name to the default filters easily."] = ""
-- L["Advanced"] = ""
-- L["A font size multiplier applied to the unit. Every text's font size in your layout will be multiplied against this value."] = ""
-- L["Aggro"] = ""
L["A height multiplier applied to the unit. Your layout's height will be multiplied against this value."] = "Um multiplicador da altura aplicada a unidade. A altura da seu leiaute será multiplicada por este valor." -- Needs review
L["Air"] = "Ar" -- Needs review
L["All"] = "Todos" -- Needs review
-- L["All enemy debuffs"] = ""
-- L["All friend buffs"] = ""
-- L["All friend debuffs"] = ""
-- L["All self buffs"] = ""
-- L["All self debuffs"] = ""
-- L["Alternate"] = ""
-- L["Alternate power"] = ""
-- L["Alternate power bar"] = ""
-- L["Always"] = ""
-- L["Always add the spell queue time to the shown latency."] = ""
-- L["Anchor"] = ""
-- L["Animate"] = ""
-- L["Animate bar changes."] = ""
-- L["Animation duration"] = ""
L["Aquatic"] = "Aquática" -- Needs review
-- L["Are you sure you want to change the filter type of a built in filter?  Doing so may break the default filtering."] = ""
-- L["Are you sure you want to change the list type of a built in filter?  Doing so may break the default filtering."] = ""
L["Are you sure you want to delete the '%s' layout? This is irreversible."] = "Você tem certeza de que deseja apagar o leiaute '%s'? Isto é irreversível." -- Needs review
L["Are you sure you want to remove this status bar?"] = "Você tem certeza de que deseja remover esta barra de status?" -- Needs review
L["Are you sure you want to remove this text?"] = "Você tem certeza de que deseja remover este texto?" -- Needs review
L["Are you sure you want to reset to defaults?"] = "Você tem certeza de que deseja redefinir para os valores padrões?" -- Needs review
L["Ascending"] = "Ascendente" -- Needs review
L["Attach to"] = "Fixar a" -- Needs review
L["Aura"] = "Aura" -- Needs review
-- L["Aura filter editor"] = ""
-- L["Aura ids"] = ""
-- L["Aura names"] = ""
L["Aura shown as if cast by someone else."] = "Aura exibida, se lançada por outro jogador." -- Needs review
L["Aura shown as if cast by you."] = "Aura exibida, se lançada por você." -- Needs review
-- L["Aura Type"] = ""
-- L["Aura types"] = ""
-- L["Auto-hide"] = ""
L["Auto-luminance"] = "Brilho automático." -- Needs review
L["Automatically adjust the luminance of the color of the outgoing heal bar to max."] = "Automaticamente ajusta ao máximo o brilho da cor da barra de curas de saída." -- Needs review
L["Automatically hide the cast bar when not casting."] = "Automaticamente esconde a barra de lançamento, quando não estiver lançando." -- Needs review
L["A width multiplier applied to the unit. Your layout's width will be multiplied against this value."] = "Um multiplicador da largura aplicada a unidade. A largura da seu leiaute será multiplicada por este valor." -- Needs review
L["Background"] = "Fundo" -- Needs review
L["Background color"] = "Cor de fundo" -- Needs review
L["Backgrounds"] = "Fundos" -- Needs review
-- L["Banzai"] = ""
-- L["Bar relation"] = ""
L["Bars"] = "Barras" -- Needs review
-- L["Battle pet"] = ""
L["Bear"] = "Urso" -- Needs review
L["Below"] = "Abaixo" -- Needs review
L["Below-left"] = "Esquerda abaixo" -- Needs review
L["Below-right"] = "Direita abaixo" -- Needs review
-- L["Blacklist"] = ""
L["Blank space"] = "Espaço em branco" -- Needs review
-- L["Blizzard currently does not provide a proper way to right-click focus with custom unit frames."] = ""
L["Blood Elf"] = "Elfo Sangrento" -- Needs review
-- L["Blood Elf enemy debuffs"] = ""
L["Blood Elf_female"] = "Elfo Sangrento" -- Needs review
-- L["Blood Elf friend buffs"] = ""
-- L["Blood Elf self buffs"] = ""
-- L["Blood Elf_short"] = ""
L["Border"] = "Borda" -- Needs review
L["Borders"] = "Bordas" -- Needs review
L["Boss"] = "Chefe" -- Needs review
-- L["Boss_short"] = ""
L["Bottom"] = "Base" -- Needs review
-- L["Bottom, Inside"] = ""
L["Bottom-left"] = "Esquerda na base" -- Needs review
-- L["Bottom-left on bottom"] = ""
-- L["Bottom-left on left"] = ""
-- L["Bottom, Outside"] = ""
L["Bottom-right"] = "Direita na base" -- Needs review
-- L["Bottom-right on bottom"] = ""
-- L["Bottom-right on right"] = ""
-- L["Buff"] = ""
-- L["Buff layout"] = ""
-- L["Buffs"] = ""
-- L["Buffs/debuffs"] = ""
-- L["Burning embers"] = ""
-- L["By class"] = ""
-- L["By group"] = ""
L["By index"] = "Por índice" -- Needs review
L["By name"] = "Por nome" -- Needs review
-- L["By raid group"] = ""
L["Cast"] = "Conjurar" -- Needs review
L["Cast bar"] = "Barra de lançamento" -- Needs review
L["Cast bar latency"] = "Latência da barra de lançamento" -- Needs review
-- L["Cast by my vehicle"] = ""
L["Caster"] = "Lançador" -- Needs review
L["Casting"] = "Lançamento" -- Needs review
L["Cast time"] = "Tempo de conjuração" -- Needs review
L["Cat"] = "Felina" -- Needs review
L["Causes the icon to pulse in the last few seconds of its lifetime."] = "Faz com que o ícone pulse, nos últimos minutos do seu tempo de vida." -- Needs review
L["Center"] = "Centro" -- Needs review
L["Change settings for unit groups."] = "Altera as definições para unidades de grupo." -- Needs review
L["Change settings for units."] = "Alterar configurações para unidades." -- Needs review
-- L["Change the current bar that you are editing."] = ""
-- L["Change the current event you are editing."] = ""
L["Change the current text that you are editing."] = "Altera o texto atual que você está editando." -- Needs review
-- L["Change the filter you are currently editing."] = ""
L["Change the layout you are currently editing."] = "Alterar o leiaute que você está editando atualmente." -- Needs review
L["Change the opacity over time smoothly."] = "Mudança de opacidade suavizada gradualmente." -- Needs review
L["Change the unit group you are currently editing."] = "Altera a unidade de grupo, que você está editando." -- Needs review
L["Change the unit you are currently editing."] = "Altera a unidade que você está editando." -- Needs review
L["Channeling"] = "Canalizando" -- Needs review
-- L["Chi"] = ""
-- L["Choose how to color this border."] = ""
-- L["Choose the border to configure."] = ""
-- L["Choose the method to determine if the unit is in range."] = ""
L["Choose the text to configure."] = "Escolha o texto a ser configurado." -- Needs review
-- L["Choose wether to grow horizontally or vertically."] = ""
L["Civilian"] = "Civil" -- Needs review
L["Class"] = "Classe"
-- L["Class abilities"] = ""
L["Class-colored"] = "Colorido por classe" -- Needs review
-- L["Click"] = ""
-- L["Click-through"] = ""
-- L["Click to pop up helpful DogTag documentation."] = ""
L["Code"] = "Código"
L["Color"] = "Cor" -- Needs review
-- L["Color by"] = ""
L["Color by class"] = "Cor por classe"
L["Color by happiness"] = "Cor para felicidade" -- Needs review
L["Color by hostility"] = "Cor para hostilidade" -- Needs review
L["Color by time"] = "Cor por tempo" -- Needs review
L["Color by type"] = "Cor por tipo" -- Needs review
L["Colored percent"] = "Por cento Colorido" -- Needs review
L["Colored raw percent"] = "Por cento Bruto Colorido" -- Needs review
L["Color for curse."] = "Cor para maldição." -- Needs review
L["Color for disease."] = "Cor para doença" -- Needs review
L["Color for enrage."] = "Cor para enfurecimento." -- Needs review
L["Color for magic."] = "Cor para mágico." -- Needs review
-- L["Color for other auras without a type."] = ""
-- L["Color for others' buffs."] = ""
-- L["Color for own buffs."] = ""
L["Color for poison."] = "Cor para veneno." -- Needs review
L["Color Icon by Element"] = "Cor do ícone por elemento." -- Needs review
L["Color NPCs by hostility"] = "Cor dos PNJ's hostis" -- Needs review
L["Color of the timer text."] = "Cor do texto do tempo." -- Needs review
-- L["Color PvP by class"] = ""
L["Colors"] = "Cores" -- Needs review
L["Color Text by Element"] = "Cor do texto por elemento" -- Needs review
L["Color that the background behind the portrait should be."] = "Cor utilizada pelo fundo atrás do retrato" -- Needs review
L["Color that the background should be."] = "Cor a ser utilizada pelo fundo." -- Needs review
L["Color that the highlight should be."] = "Cor a ser utilizada pelo realçamento." -- Needs review
L["Color the bar by hostility for NPCs."] = "Colore a barra de hostilidade para PNJ's." -- Needs review
-- L["Color the bar by hostility for player characters.  Note that color by class takes precedence over this."] = ""
-- L["Color the bar by the units' happiness."] = ""
-- L["Color the bar by unit class"] = ""
-- L["Color the bar for PvP enemies by unit class."] = ""
L["Color the text by the time remaining on the aura."] = "Colore o texto pelo tempo remanescente na aura." -- Needs review
L["Columns left"] = "Colunas para esquerda" -- Needs review
L["Column spacing"] = "Espaçamento das colunas" -- Needs review
L["Columns right"] = "Colunas para direita" -- Needs review
L["Combat fader"] = "Fader de combate" -- Needs review
L["Combat icon"] = "Ícone de combate"
L["Combat text"] = "Texto de combate."
L["Combo points"] = "Pontos de combo."
L["Complete"] = "Completo" -- Needs review
L["Config mode"] = "Modo de Configuração"
-- L["Configure every detail of the aura filtering."] = ""
L["Configure how the units in the group will be ordered and positioned."] = "Configura como as unidades em grupo serão ordenadas e posicionadas." -- Needs review
-- L["Configure the borders that are applied around the auras."] = ""
-- L["Configure the filters for the aura modules."] = ""
L["Configure the text displayed on auras."] = "Configura o texto exibido nas auras" -- Needs review
-- L["Configure what auras trigger a highlight."] = ""
L["Configure when the group will be shown and if units will be filtered."] = "Configura quando o grupo será exibido e se as unidades serão filtradas." -- Needs review
-- L["Count"] = ""
-- L["Create a new filter.  This will copy the data of the currently-selected filter."] = ""
L["Create a new group. This will copy the data of the currently-selected group."] = "Cria um novo grupo. Isto copiará os dados do grupo atualmente selecionado." -- Needs review
L["Create a new layout. This will copy the data of the currently-selected layout."] = "Criar um novo leiaute. Irá copiar todos os dados do leiaute selecionado atualmente." -- Needs review
-- L["Current bar"] = ""
-- L["Current border"] = ""
L["Current event"] = "Evento corrente" -- Needs review
-- L["Current filter"] = ""
L["Current group"] = "Grupo atual" -- Needs review
L["Current layout"] = "Leiaute atual" -- Needs review
L["Current text"] = "Texto atual" -- Needs review
L["Current unit"] = "Unidade atual" -- Needs review
L["Curse"] = "Maldição" -- Needs review
L["Custom"] = "Customizado"
-- L["Custom background"] = ""
L["Custom color"] = "Cor customizada" -- Needs review
-- L["Custom item"] = ""
-- L["Custom rested"] = ""
-- L["Custom spell"] = ""
L["Dead"] = "Morto" -- Needs review
L["Death Knight"] = "Cavaleiro da Morte" -- Needs review
-- L["Death Knight enemy debuffs"] = ""
L["Death Knight_female"] = "Cavaleira da Morte" -- Needs review
-- L["Death Knight friend buffs"] = ""
-- L["Death Knight pet buffs"] = ""
L["Death Knights"] = "Cavaleiros da Morte" -- Needs review
-- L["Death Knight self buffs"] = ""
-- L["Death Knight_short"] = ""
-- L["Debuff"] = ""
-- L["Debuff layout"] = ""
-- L["Debuffs"] = ""
L["Default"] = "Padrão" -- Needs review
-- L["Default buffs"] = ""
-- L["Default buffs, mine"] = ""
-- L["Default debuffs"] = ""
-- L["Default debuffs, mine"] = ""
L["Default font"] = "Fonte padrão" -- Needs review
L["Default size"] = "Tamanho padrão" -- Needs review
L["Default size of the text, acts as a multiplier to all other texts."] = "Tamanho padrão do texto, age como um multiplicador de todos os outros textos." -- Needs review
L["Default texture"] = "Textura padrão" -- Needs review
L["Deficit"] = "Déficit "
-- L["Define your preferred order in which the lements will be displayed. The numbers describe positions from left to right."] = ""
L["Delete"] = "Apagar" -- Needs review
L["Delete current event."] = "Evento corrente apagado." -- Needs review
-- L["Delete current filter."] = ""
L["Delete this layout."] = "Apagar este leiaute." -- Needs review
-- L["Demonic fury"] = ""
L["Descending"] = "Descendente" -- Needs review
-- L["Dialog"] = ""
L["Did you know?"] = "Você sabia?" -- Needs review
L["Difference"] = "Diferença"
L["Direction that the auras will grow."] = "Direção em que as auras crescerão." -- Needs review
L["Disable"] = "Desabilitar" -- Needs review
-- L["Disable capturing clicks on aura icons allowing the clicks to fall through to the window underneath the aura."] = ""
-- L["Disabled in the Blizzard addon list."] = ""
-- L["Disabling PitBull4 config mode, entering combat."] = ""
-- L["Disabling PitBull4 config mode, entering pet battle."] = ""
L["Disconnected"] = "Desconectado" -- Needs review
L["Disease"] = "Doença" -- Needs review
-- L["Dispellable"] = ""
-- L["Dispellable by me or extra friend"] = ""
-- L["Dispellable or extra friend"] = ""
-- L["Dispel type"] = ""
L["Display"] = "Exibição" -- Needs review
-- L["Display icons for the eclipse buffs on the bar."] = ""
-- L["Display the eclipse bar as a vertical bar instead of a horizontal bar."] = ""
-- L["Display when"] = ""
L["DogTag-3.0 texts"] = "Textos do DogTag-3.0"
-- L["DogTag help"] = ""
-- L["Down then left"] = ""
-- L["Down then right"] = ""
-- L["Draenei"] = ""
L["Draenei_female"] = "Draenea" -- Needs review
-- L["Draenei friend buffs"] = ""
-- L["Draenei_short"] = ""
L["Drain the bar instead of filling it."] = "Esvaziar a barra ao invés de enche-la."
L["Druid"] = "Druida" -- Needs review
L["Druid can dispel"] = "Druida pode dissipar" -- Needs review
-- L["Druid can purge"] = ""
-- L["Druid enemy debuffs"] = ""
L["Druid_female"] = "Druidesa" -- Needs review
-- L["Druid friend buffs"] = ""
L["Druid mana"] = "Mana do druida" -- Needs review
-- L["Druid/Monk mana bar"] = ""
L["Druids"] = "Druidas" -- Needs review
-- L["Druid self buffs"] = ""
-- L["Druid_short"] = ""
-- L["Duel (~10 yards)"] = ""
-- L["Duration"] = ""
-- L["Dwarf"] = ""
L["Dwarf_female"] = "Anã" -- Needs review
-- L["Dwarf friend buffs"] = ""
-- L["Dwarf self buffs"] = ""
-- L["Dwarf_short"] = ""
L["Earth"] = "Terra" -- Needs review
-- L["Eclipse"] = ""
L["Edge"] = "Canto" -- Needs review
-- L["Edit bar"] = ""
L["Edit event"] = "Editar evento" -- Needs review
L["Edit text"] = "Editar texto" -- Needs review
L["Edit the way your frames look, including the controls on your frames."] = "Modifique a aparência de seus quadros, incluindo os controles nos seus quadros."
-- L["Edit which units the event triggers updates on."] = ""
L["Elements"] = "Elementos" -- Needs review
L["Elite"] = "Elite" -- Needs review
-- L["Elite_short"] = ""
-- L["Empty health"] = ""
L["Empty opacity"] = "Opacidade vazia" -- Needs review
L["Enable"] = "Habilitar" -- Needs review
-- L["Enable aura highlighting for this layout."] = ""
L["Enabled"] = "Habilitado" -- Needs review
-- L["Enable display of buffs."] = ""
-- L["Enable display of debuffs."] = ""
L["Enable display of temporary weapon enchants."] = "Habilita a exibição de encantamentos temporários para armas." -- Needs review
L["Enables tooltips when hovering over the icons."] = "Habilita dicas, quando pairar o mouse sobre os ícones." -- Needs review
-- L["Enable this border."] = ""
L["Enable this fader."] = "Habilitar este fader." -- Needs review
L["Enable this indicator."] = "Habilitar este indicador." -- Needs review
L["Enable this module for this layout."] = "Habilitar este módulo para este leiaute." -- Needs review
L["Enable this status bar."] = "Habilitar esta barra de status." -- Needs review
-- L["Enable this status bar provider."] = ""
L["Enable this text."] = "Habilitar este texto." -- Needs review
L["Enable this unit."] = "Habilitar esta unidade." -- Needs review
-- L["Enable this unit group."] = ""
L["Enemy"] = "Inimigo" -- Needs review
-- L["Enemy debuffs"] = ""
L["Enrage"] = "Enfurecimento" -- Needs review
L["Enter a LibDogTag-3.0 code tag. You can type /dog into your chat for help."] = "Entre uma tag de código do LibDogTag-3.0. Você pode digitar /dog no seu bate-papo." -- Needs review
L["Enter a Lua script."] = "Entre com um script Lua." -- Needs review
-- L["Enter the name of the item you want use to check the range with."] = ""
-- L["Enter the name of the spell you want use to check the range with."] = ""
-- L["Enter the unit to compare the caster of the aura against."] = ""
-- L["Enter the unit to compare the unit the aura is on against."] = ""
-- L["Enter the value to compare the count against."] = ""
-- L["Enter the value to compare the duration against."] = ""
-- L["Enter the value to compare the rank against."] = ""
-- L["Enter the value to compare the time left against."] = ""
-- L["Equal"] = ""
L["Events"] = "Eventos" -- Needs review
L["Events to cause the text to update."] = "Eventos que fazem o texto ser atualizado." -- Needs review
L["Experience"] = "Experiência" -- Needs review
L["Experience bar"] = "Barra de experiência"
L["Expiry pulse"] = "Pulso de expiração" -- Needs review
L["Expiry time"] = "Tempo de expiração" -- Needs review
-- L["Extra buffs"] = ""
-- L["Extra enemy debuffs"] = ""
-- L["Extra enemy highlights"] = ""
-- L["Extra friend debuffs"] = ""
-- L["Extra friend highlights"] = ""
-- L["Fade"] = ""
L["Faders"] = "Transparência" -- Needs review
L["Faders cause the unit frame to become more or less opaque on certain conditions."] = "Transparência fazem o frame da unidade ficar mais ou menos opacos em certas condições." -- Needs review
-- L["Fade the bar changes."] = ""
L["Failed"] = "Falha" -- Needs review
L["Fallback style"] = "Estilo recuado" -- Needs review
L["False"] = "Falso" -- Needs review
-- L["Feigned Death"] = ""
-- L["Filter"] = ""
-- L["Filter by if the aura is a buff or not."] = ""
-- L["Filter by if the aura is eligible for consolidation."] = ""
-- L["Filter by if the aura is weapon enchant or not."] = ""
-- L["Filter by if the debuff is stealable or not."] = ""
-- L["Filter by if the debuff is yours or not."] = ""
L["Filtering"] = "Filtragem" -- Needs review
-- L["Filter of that name already exists."] = ""
-- L["Filters"] = ""
-- L["Filter type"] = ""
L["Fire"] = "Fogo" -- Needs review
L["Fixed size"] = "Tamanho fixo" -- Needs review
-- L["Fixed time at then end of a running cast where you are able to cast the next spell. Default is %s\\nWARNING: Do not change this unless you know exactly what you're doing!"] = ""
L["Flight"] = "Voadora" -- Needs review
L["Focus"] = "Foco"
-- L["Focus-target"] = ""
-- L["Follow (~28 yards)"] = ""
L["Font"] = "Fonte" -- Needs review
-- L["Font size"] = ""
-- L["Font size multiplier"] = ""
-- L["Font size to use on this indicator."] = ""
-- L["Frame level"] = ""
-- L["Frame movement"] = ""
-- L["Frame relation"] = ""
L["Friend"] = "Amigo" -- Needs review
-- L["Friend buffs"] = ""
-- L["Friend debuffs"] = ""
L["Friendly opacity"] = "Opacidade amigável" -- Needs review
L["Full body"] = "Corpo inteiro" -- Needs review
-- L["Full health"] = ""
L["Full opacity"] = "Opacidade cheia" -- Needs review
-- L["Gaps for missing pets"] = ""
L["General"] = "Geral" -- Needs review
L["Ghost"] = "Fantasma" -- Needs review
L["Globally enable this module."] = "Habilitar este módulo globalmente." -- Needs review
L["Gnome"] = "Gnomo" -- Needs review
L["Gnome_female"] = "Gnomida" -- Needs review
-- L["Gnome friend buffs"] = ""
-- L["Gnome_short"] = ""
-- L["Goblin"] = ""
-- L["Goblin_female"] = ""
-- L["Goblin friend buffs"] = ""
-- L["Goblin_short"] = ""
-- L["Greater than"] = ""
-- L["Greater than or equal"] = ""
L["Groups"] = "Grupos" -- Needs review
L["Growth direction"] = "Direção de crescimento" -- Needs review
-- L["Half health"] = ""
L["Happiness icon"] = "Ícone de Felicidade"
L["Health"] = "Vida" -- Needs review
-- L["Health bar"] = ""
L["Height"] = "Altura" -- Needs review
L["Height multiplier"] = "Multiplicador da altura" -- Needs review
L["Height of the unit frame."] = "Altura do quadro da unidade." -- Needs review
L["Height type"] = "Tipo de altura" -- Needs review
-- L["Helpful spells (~40 yards)"] = ""
-- L["Hide Blizzard frames"] = ""
-- L["Hide Blizzard frames that are no longer needed."] = ""
L["Hide if full"] = "Esconder, se cheio" -- Needs review
L["Hide inactive"] = "Esconde, se inativo" -- Needs review
-- L["Hide non-mana"] = ""
-- L["Hide non-power"] = ""
L["Hides inactive totem icons completely."] = "Esconde os ícones de totens inativos, completamente." -- Needs review
-- L["Hides the power bar if the unit has no power."] = ""
-- L["Hides the power bar if the unit's current power is not mana."] = ""
-- L["Hides the standard alternate power bar shown in some encounters and quests."] = ""
-- L["Hides the standard buff/debuff frame in the top-right corner of the screen."] = ""
-- L["Hides the standard cast bar."] = ""
L["Hides the standard rune bar in the top-left corner of the screen."] = "Esconde a barra de runas padrão no canto superior esquerdo da tela." -- Needs review
-- L["Hide the standard focus frame."] = ""
-- L["Hide the standard party frames."] = ""
-- L["Hide the standard player frame."] = ""
-- L["Hide the standard raid manager and raid frames and party frames (when set to use raid style in blizzard interface options)."] = ""
-- L["Hide the standard target frame."] = ""
L["Hide when at 100% mana."] = "Esconder, quando possuir 100% de mana." -- Needs review
-- L["High"] = ""
L["Highlight"] = "Realçar" -- Needs review
-- L["Highlight: all friend debuffs"] = ""
-- L["Highlight: dispellable by me debuffs"] = ""
-- L["Highlight: dispellable debuffs"] = ""
-- L["Highlight: Enemy buffs"] = ""
-- L["Highlight: Friend debuffs"] = ""
-- L["Highlight: purgeable buffs"] = ""
-- L["Highlight: purgeable by me buffs"] = ""
-- L["Highlights"] = ""
-- L["Highlight this unit frame when it is the same as your current target."] = ""
-- L["Holy power"] = ""
L["Horizontal"] = "Horizontal" -- Needs review
L["Horizontal offset"] = "Deslocamento horizontal" -- Needs review
L["Horizontal position"] = "Posição horizontal" -- Needs review
L["Horizontal position on the x-axis of the screen."] = "Posição horizontal no eixo \"x\" da tela." -- Needs review
L["Horizontal spacing"] = "Espaçamento horizontal" -- Needs review
L["Hostile opacity"] = "Opacidade hostil" -- Needs review
L["Hostility-colored"] = "Colorido por hostilidade" -- Needs review
L["Hostility fader"] = "Esvaecedor de hostilidade" -- Needs review
-- L["Hours"] = ""
-- L["how an icon based on whether or not the unit is a quest boss."] = ""
-- L["How far in pixels that indicators are horizontally placed inside bars."] = ""
-- L["How far in pixels that indicators are horizontally placed inside the unit frame."] = ""
-- L["How far in pixels that indicators are placed outside of bars."] = ""
-- L["How far in pixels that indicators are placed outside the unit frame."] = ""
-- L["How far in pixels that indicators are vertically placed inside bars."] = ""
-- L["How far in pixels that indicators are vertically placed inside the unit frame."] = ""
L["How far the border should be from the frame."] = "Quão distante a borda deverá ser a partir do quadro." -- Needs review
L["How large the border should be."] = "Quão larga a borda deve ser." -- Needs review
L["How many pixels between columns in this group."] = "Quantidade de pixels entre as colunas neste grupo." -- Needs review
L["How many pixels between rows in this group."] = "Quantidade de pixels entre as linhas neste grupo." -- Needs review
L["How many totems to draw per line."] = "Quantos totens desenhar por linha." -- Needs review
-- L["How much spacing to show between combo points."] = ""
L["How opaque the empty section of the bar is."] = "O quão opaca é a seção vazia da barra."
L["How opaque the full section of the bar is."] = "O quão opaca é a seção cheia da barra."
L["How tall the bar should be in relation to other bars."] = "O quão alta a barra deve ser em relação às outras barras." -- Needs review
-- L["How tall the indicator should be in relation to other bars."] = ""
L["How to sort the frames within the group."] = "Como ordenar os retratos dentro do grupo." -- Needs review
L["How wide the bar should be in relation to other bars."] = "O quão larga a barra deve ser em relação às outras barras."
L["Human"] = "Humano" -- Needs review
L["Human_female"] = "Humana" -- Needs review
-- L["Human friend buffs"] = ""
-- L["Human_short"] = ""
L["Hunter"] = "Caçador" -- Needs review
L["Hunter can dispel"] = "Caçador pode dissipar" -- Needs review
-- L["Hunter can purge"] = ""
-- L["Hunter enemy debuffs"] = ""
L["Hunter_female"] = "Caçadora" -- Needs review
-- L["Hunter friend buffs"] = ""
-- L["Hunter friend debuffs"] = ""
-- L["Hunter pet buffs"] = ""
L["Hunters"] = "Caçadores" -- Needs review
-- L["Hunter self buffs"] = ""
-- L["Hunter_short"] = ""
L["Hurt opacity"] = "Opacidade de Machucado" -- Needs review
L["Icon"] = "Ícone" -- Needs review
L["Icon position"] = "Posição do ícone" -- Needs review
-- L["Icons"] = ""
L["Icon size"] = "Tamanho do ícone" -- Needs review
-- L["Icon size for my auras"] = ""
-- L["Idle background"] = ""
-- L["Ids of the auras you want the filter to include or exclude."] = ""
-- L["If you want more fonts, you should install the addon 'SharedMedia'."] = ""
-- L["If you want more textures, you should install the addon 'SharedMedia'."] = ""
-- L["Inactive color"] = ""
-- L["Include GCD lockout"] = ""
L["Include %s"] = "Inclui %s" -- Needs review
L["Include %s as part of the unit group."] = "Inclui %s como parte da unidade de grupo." -- Needs review
-- L["Include spell queue time"] = ""
L["In-combat opacity"] = "Opacidade em combate"
L["Incoming color"] = "Cor de entrada" -- Needs review
L["Indicators"] = "Indicadores"
L["Indicators are icons or other graphical displays that convey a specific, usually temporary, status."] = "Indicadores são ícones ou outros gráficos que mostram um status específico, usualmente temporário."
L["Informational"] = "Informativo"
-- L["Initiate a ready check, asking your group members if they are ready to continue."] = ""
-- L["Initiate a role check, asking your group members to specify their roles."] = ""
L["Inside"] = "Dentro" -- Needs review
-- L["Inside horizontal padding"] = ""
-- L["Inside vertical padding"] = ""
L["Interruptible"] = "Interrompível" -- Needs review
L["is"] = "é" -- Needs review
-- L["Is buff"] = ""
L["is enemy"] = "É inimigo" -- Needs review
L["is friend"] = "é amigo" -- Needs review
L["Is mine"] = "É meu" -- Needs review
L["is not"] = "não é" -- Needs review
L["Is stealable"] = "É possível ser roubado" -- Needs review
L["Is weapon enchant"] = "É arma encantada" -- Needs review
L["Latency"] = "Latência" -- Needs review
-- L["Layering of the unit frame relative to other frames."] = ""
-- L["Layer the unit frame will be on."] = ""
L["Layout"] = "Leiaute" -- Needs review
L["Layout editor"] = "Editor de leiaute" -- Needs review
L["Leader icon"] = "Ícone do líder" -- Needs review
-- L["Leave gaps in the spacing for pets that do not exist."] = ""
L["Left"] = "Esquerda" -- Needs review
L["Left-bottom"] = "Esquerda na base" -- Needs review
-- L["Left, Outside"] = ""
-- L["Left then down"] = ""
-- L["Left then up"] = ""
L["Left-top"] = "Esquerda no topo" -- Needs review
-- L["Less than"] = ""
-- L["Less than or equal"] = ""
-- L["Level of the unit frame within the layer."] = ""
-- L["Limit how frames may be moved."] = ""
L["Limit number of displayed auras."] = "Número limite de auras exibidas." -- Needs review
-- L["List type"] = ""
L["Location"] = "Localização" -- Needs review
-- L["Locked"] = ""
L["Long"] = "Extenso"
L["Long w/ Druid form"] = "Comprido c/ Forma de Druida" -- Needs review
-- L["Low"] = ""
L["Lua texts"] = "Textos Lua" -- Needs review
L["Mage"] = "Mago" -- Needs review
L["Mage can dispel"] = "Mago pode dissipar" -- Needs review
-- L["Mage can purge"] = ""
-- L["Mage enemy debuffs"] = ""
L["Mage_female"] = "Maga" -- Needs review
-- L["Mage friend buffs"] = ""
-- L["Mage friend debuffs"] = ""
L["Mages"] = "Magos" -- Needs review
-- L["Mage self buffs"] = ""
-- L["Mage self debuffs"] = ""
-- L["Mage_short"] = ""
L["Magic"] = "Mágico" -- Needs review
L["Main assist"] = "Assistente principal" -- Needs review
L["Main assists"] = "Assistentes principais" -- Needs review
L["Main Background"] = "Fundo principal" -- Needs review
L["Main tank"] = "Tanque principal" -- Needs review
L["Main tanks"] = "Tanques principais"
L["Make the unit frame fade depending on the units hostility."] = "Faz com que o retrato da unidade esvaeça, de acordo com a sua hostilidade." -- Needs review
L["Make the unit frame fade if out of combat."] = "Faz com que o quadro da unidade desapareça gradualmente fora de combate."
L["Make the unit frame fade if out of range."] = "Faz o retrato da unidade esvaecer, caso esta esteja fora do campo de visão." -- Needs review
L["Mana spark"] = "Faísca de mana" -- Needs review
L["Map"] = "Mapa" -- Needs review
L["Map type"] = "Tipo de mapa" -- Needs review
L["Master looter icon"] = "Ícone do saqueador mestre." -- Needs review
L["Maximum opacity"] = "Opacidade máxima" -- Needs review
-- L["Medium"] = ""
-- L["Meta"] = ""
L["Middle"] = "Meio"
L["Mine"] = "Meu" -- Needs review
L["Mini"] = "Mini"
-- L["Minimap icon"] = ""
L["Minimum opacity"] = "Opacidade mínima" -- Needs review
-- L["Minutes"] = ""
L["Mirror horizontally"] = "Espelhar horizontalmente" -- Needs review
L["Mirror vertically"] = "Espelhar verticalmente" -- Needs review
L["Modules"] = "Módulos" -- Needs review
L["Modules provide actual functionality for PitBull."] = "Os módulos oferecem funcionalidade real para o PitBull." -- Needs review
-- L["Monk"] = ""
-- L["Monk can dispel"] = ""
-- L["Monk enemy debuffs"] = ""
-- L["Monk friend buffs"] = ""
-- L["Monks"] = ""
-- L["Monk self buffs"] = ""
L["Moonkin"] = "Luniscante" -- Needs review
L["Mouse-over"] = "Mouse sobreposto" -- Needs review
L["Multiplicative scale of the unit frame."] = "Escala multiplicativa do quadro da unidade." -- Needs review
-- L["Must be a number."] = ""
L["Must be at least 3 characters long."] = "Precisa conter pelo menos 3 caracteres." -- Needs review
-- L["Must be a valid spell id."] = ""
L["Must be a valid unit id."] = "Deve ser uma id de unidade válida." -- Needs review
-- L["My class can dispel"] = ""
-- L["My class can purge"] = ""
-- L["My class enemy debuffs"] = ""
-- L["My class friend buffs"] = ""
-- L["My class friend debuffs"] = ""
-- L["My class pet buffs"] = ""
-- L["My class self buffs"] = ""
-- L["My class self debuffs"] = ""
-- L["My own buffs"] = ""
-- L["My own buffs count"] = ""
-- L["My own buffs on enemy units"] = ""
-- L["My own buffs on friendly units"] = ""
-- L["My own buffs time remaining"] = ""
-- L["My own debuffs"] = ""
-- L["My own debuffs count"] = ""
-- L["My own debuffs on enemy units"] = ""
-- L["My own debuffs on friendly units"] = ""
-- L["My own debuffs time remaining"] = ""
-- L["My race enemy debuffs"] = ""
-- L["My race friend buffs"] = ""
-- L["My race self buffs"] = ""
-- L["My race self debuffs"] = ""
L["Name"] = "Nome" -- Needs review
-- L["Names of the auras you want the filter to include or exclude."] = ""
-- L["Never"] = ""
-- L["New bar"] = ""
-- L["New column on resize"] = ""
L["New event"] = "Novo evento" -- Needs review
-- L["New filter"] = ""
L["New group"] = "Novo grupo" -- Needs review
-- L["New id"] = ""
L["New layout"] = "Novo leiaute"
-- L["New name"] = ""
-- L["New row on resize"] = ""
L["New text"] = "Novo texto" -- Needs review
L["Night Elf"] = "Elfo Noturno" -- Needs review
L["Night Elf_female"] = "Elfa Noturna" -- Needs review
-- L["Night Elf friend buffs"] = ""
-- L["Night Elf self buffs"] = ""
-- L["Night Elf_short"] = ""
-- L["No"] = ""
-- L["No LibSharedMedia detected"] = ""
-- L["None"] = ""
L["Normal"] = "Normal" -- Needs review
L["Note"] = "Nota" -- Needs review
-- L["Not equal"] = ""
L["Number of pixels to offset the auras from the start point horizontally."] = "Número de pixels a deslocar as auras, a partir do ponto inicial, horizontalmente." -- Needs review
-- L["Number of pixels to offset the auras from the start point vertically."] = ""
-- L["Number of pixels to offset the text from the anchor point horizontally."] = ""
-- L["Number of pixels to offset the text from the anchor point vertically."] = ""
-- L["On mouse-over"] = ""
L["Open a standlone config window, allowing you to actually configure PitBull Unit Frames 4.0."] = "Abre uma janela de configuração autônoma, permitindo que você realmente configure  o PitBull Unit Frames 4.0." -- Needs review
-- L["Operator"] = ""
-- L["Operator to use to combine the filters."] = ""
L["Options related to the pulsing visualisation."] = "Opções relacionadas à visualização da pulsação." -- Needs review
L["Options relating to sound effects on totem events."] = "Opções relacionadas a efeitos de som, nos eventos dos totens." -- Needs review
-- L["Options relating to the spiral display timer."] = ""
L["Options relating to the text display timer."] = "Opções relacionadas ao temporizador de exibição de textos." -- Needs review
L["Options that apply to all indicators."] = "Opções que se aplicam a todos os indicadores." -- Needs review
L["Options that apply to all status bars."] = "Opções que se aplicam a todas as barras de status." -- Needs review
-- L["Options that apply to PitBull in general and/or all its unit frames."] = ""
-- L["Orc"] = ""
L["Orc_female"] = "Orquisa" -- Needs review
-- L["Orc friend buffs"] = ""
-- L["Orc self buffs"] = ""
-- L["Orc self debuffs"] = ""
-- L["Orc_short"] = ""
L["Order"] = "Ordem" -- Needs review
L["Other"] = "Outro" -- Needs review
L["Others"] = "Outros" -- Needs review
-- L["Others' buffs"] = ""
-- L["Others' buffs count"] = ""
-- L["Others' buffs on enemy"] = ""
-- L["Others' buffs on friendly units"] = ""
-- L["Others' buffs time remaining"] = ""
-- L["Others' debuffs"] = ""
-- L["Others' debuffs count"] = ""
-- L["Others' debuffs on enemy units"] = ""
-- L["Others' debuffs on friendly units"] = ""
-- L["Others' debuffs time remaining"] = ""
L["Outgoing color (no overheal)"] = "Cor de saída (sem cura excedente)" -- Needs review
L["Outgoing color (overheal)"] = "Cor de saída (cura excedente)" -- Needs review
-- L["Out of combat"] = ""
L["Out-of-combat opacity"] = "Opacidade de Fora de Combate"
L["Out-of-range opacity"] = "Opacidade fora do campo de visão" -- Needs review
L["Outside"] = "Fora" -- Needs review
-- L["Outside margin"] = ""
-- L["Padding"] = ""
-- L["Padding in pixels between bars and the sides of the unit frame."] = ""
L["Paladin"] = "Paladino" -- Needs review
L["Paladin can dispel"] = "Paladino pode dissipar" -- Needs review
-- L["Paladin enemy debuffs"] = ""
L["Paladin_female"] = "Paladina" -- Needs review
-- L["Paladin friend buffs"] = ""
-- L["Paladin friend debuffs"] = ""
L["Paladins"] = "Paladinos" -- Needs review
-- L["Paladin self buffs"] = ""
-- L["Paladin_short"] = ""
-- L["Pandaren"] = ""
-- L["Pandaren enemy debuffs"] = ""
-- L["Pandaren friend buffs"] = ""
L["Party"] = "Grupo"
L["Party member #%d"] = "Membro do grupo #%d" -- Needs review
L["Party pet"] = "Ajudante do grupo"
L["Party pets"] = "Ajudantes do grupo"
L["Percent"] = "Porcentagem"
-- L["Percentage of side"] = ""
L["Pet"] = "Companhia" -- Needs review
L["Pet happiness"] = "Felicidade da companhia" -- Needs review
L["PitBull"] = "PitBull" -- Needs review
-- L["PitBull4_Banzai requires the HealthBar module"] = ""
-- L["PitBull4_Banzai requires the library LIbBanzai-2.0 to be available."] = ""
-- L["PitBull4_CastBarLatency requires the CastBar module"] = ""
-- L["PitBull4_VisualHeal requires the library LibHealComm-3.0 to be available."] = ""
L["PitBull Unit Frames 4.0"] = "PitBull Quadros de Unidade 4.0" -- Needs review
L["Play certain sounds when various unit-based events occur."] = "Executa sons específicos, quando diversos eventos baseados nas unidades ocorrem." -- Needs review
L["Player"] = "Jogador"
L["Player class"] = "Classe do jogador" -- Needs review
L["Player classes only"] = "Apenas classes de jogador" -- Needs review
-- L["Player race"] = ""
L["Player's pet"] = "Ajudante"
L["Poison"] = "Veneno" -- Needs review
L["Portrait"] = "Retrato" -- Needs review
L["Position"] = "Posição" -- Needs review
-- L["Position as bar"] = ""
L["Position %i (Currently: %s)"] = "Posição %i (Corrente: %s)" -- Needs review
L["Power"] = "Poder" -- Needs review
L["Power bar"] = "Barra de poder" -- Needs review
L["Priest"] = "Sacerdote" -- Needs review
L["Priest can dispel"] = "Sarcedote pode dissipar" -- Needs review
-- L["Priest can purge"] = ""
-- L["Priest enemy debuffs"] = ""
L["Priest_female"] = "Sacerdotisa" -- Needs review
-- L["Priest friend buffs"] = ""
-- L["Priest friend debuffs"] = ""
L["Priests"] = "Sacerdotes" -- Needs review
-- L["Priest self buffs"] = ""
-- L["Priest self debuffs"] = ""
-- L["Priest_short"] = ""
-- L["Problem upgrading PitBull4 config_version %d to %d.  Please file a ticket and attach your WTF/Account/$ACCOUNT/SavedVariables/PitBull4.lua file!"] = ""
L["Provide empty bars for spacing."] = "Provê barras vazias para espaçamento." -- Needs review
L["Pulse for this many seconds before the totem runs out."] = "Pulse por tanto segundos, antes do totem se esgotar." -- Needs review
L["Pulsing"] = "Pulsação" -- Needs review
-- L["Purgeable"] = ""
-- L["Purgeable by me or extra enemy"] = ""
L["PvP icon"] = "Ícone JxJ" -- Needs review
-- L["PVPTimer"] = ""
-- L["Quest icon"] = ""
-- L["Queue time"] = ""
L["Raid"] = "Raide"
-- L["Raid member #%d"] = ""
L["Raid pet"] = "Ajudante da raide"
L["Raid pets"] = "Ajudantes da raide"
L["Raid target icon"] = "Ícone de alvo de raide" -- Needs review
-- L["Range check method"] = ""
L["Range fader"] = "Alcance de esvaecimento" -- Needs review
-- L["Rank"] = ""
L["Rare"] = "Raro" -- Needs review
L["Rare-Elite"] = "Elite-raro" -- Needs review
-- L["Rare-Elite_short"] = ""
-- L["Rare_short"] = ""
L["Raw percent"] = "Por cento Bruto" -- Needs review
L["Reaction"] = "Reação" -- Needs review
L["Ready check icon"] = "Ícone de confirmação de \"pronto\"" -- Needs review
L["Remove"] = "Remover" -- Needs review
-- L["Remove a name from the list."] = ""
-- L["Remove an id from the list."] = ""
-- L["Remove id"] = ""
-- L["Remove name"] = ""
L["Remove this status bar."] = "Remove esta barra de status." -- Needs review
L["Remove this text."] = "Remover este texto." -- Needs review
L["Remove this unit group. Note: there is no way to recover after removal."] = "Remove esta unidade de grupo. Nota: não há como recuperá-la, após a remoção." -- Needs review
L["Rename the '%s' text."] = "Renomear o texto '%s'." -- Needs review
L["Rename the '%s' unit group."] = "Renomeia a '%$' unidade de grupo." -- Needs review
L["Reputation"] = "Reputação" -- Needs review
L["Reputation bar"] = "Barra de reputação" -- Needs review
L["Reset to defaults"] = "Redefinir para valores padrões." -- Needs review
L["Rest icon"] = "Ícone de descanso" -- Needs review
L["Reverse"] = "Inverter"
L["Reverse order in which auras are displayed."] = "Reverte a ordem em que as auras são exibidas." -- Needs review
L["Reverse the direction of the bar, filling from right-to-left instead of left-to-right."] = "Inverte a direção da barra, preenchendo-a da direita para a esquerda ao invés de esquerda para a direita."
L["Right"] = "Direita"
L["Right-bottom"] = "Direita na base" -- Needs review
-- L["Right-click"] = ""
-- L["Right, Outside"] = ""
-- L["Right then down"] = ""
-- L["Right then up"] = ""
L["Right-top"] = "Direita no topo" -- Needs review
L["Rogue"] = "Ladino" -- Needs review
L["Rogue can dispel"] = "Ladino pode dissipar" -- Needs review
-- L["Rogue can purge"] = ""
-- L["Rogue enemy debuffs"] = ""
L["Rogue_female"] = "Ladina" -- Needs review
-- L["Rogue friend buffs"] = ""
L["Rogues"] = "Ladinos" -- Needs review
-- L["Rogue self buffs"] = ""
-- L["Rogue_short"] = ""
-- L["Role icon"] = ""
L["Rows down"] = "Linhas abaixo" -- Needs review
L["Row spacing"] = "Espaçamento das linhas" -- Needs review
L["Rows up"] = "Linhas acima" -- Needs review
L["Rune bar"] = "Barra de runas." -- Needs review
-- L["Runes"] = ""
-- L["Sample aura created by PitBull to allow you to see the results of your configuration easily."] = ""
-- L["Sample Buff"] = ""
-- L["Sample Debuff"] = ""
-- L["Sample tempoary weapon enchant created by PitBull to allow you to see the results of your configuration easily."] = ""
-- L["Sample Weapon Enchant"] = ""
L["Scale"] = "Escala" -- Needs review
-- L["Seconds"] = ""
-- L["Select a filter to use for highlighting auras."] = ""
L["Select a filter to use for the class."] = "Selecione um filtro a ser utilizado pela classe" -- Needs review
L["Select a filter to use for the race."] = "Selecione um filtro para a raça." -- Needs review
-- L["Select a filter to use in this meta filter."] = ""
-- L["Select buffs to show on your friends."] = ""
-- L["Select debuffs to show on your enemies."] = ""
-- L["Select debuffs to show on your friends."] = ""
-- L["Select extra buffs to highlight on your enemies."] = ""
-- L["Select extra debuffs to highlight on your friends."] = ""
L["Select how to configure the height setting."] = "Seleciona como configurar as definições de altura." -- Needs review
L["Select how to configure the width setting."] = "Seleciona como configurar as definições de largura." -- Needs review
-- L["Select if the list of ids are treated as a whitelist or blacklist. A whitelist will only display the selected auras and a blacklist will only show unchecked or unlisted auras."] = ""
-- L["Select if the list of names are treated as a whitelist or blacklist. A whitelist will only display the selected auras and a blacklist will only show unchecked or unlisted auras."] = ""
-- L["Select the filters to be used to limit the auras that are displayed."] = ""
-- L["Select the operator to compare the count against the value."] = ""
-- L["Select the operator to compare the duration against the value."] = ""
-- L["Select the operator to compare the rank against the value."] = ""
-- L["Select the operator to compare the time left against the value."] = ""
-- L["Select the style of the highlight for this layout."] = ""
-- L["Select the time units the value represents."] = ""
-- L["Select the units that this event will trigger text updates on."] = ""
L["Self"] = "Em si" -- Needs review
-- L["Set colors that PitBull uses."] = ""
-- L["Set how many frame levels auras are above the frame."] = ""
-- L["Set how tall the auras will be allowed to grow as a percentage of the height of the frame they are attached to."] = ""
-- L["Set how wide the auras will be allowed to grow as a percentage of the width of the frame they are attached to."] = ""
-- L["Set size of icons of auras cast by me."] = ""
L["Set size of the aura icons."] = "Define o tamanho do ícone das auras." -- Needs review
L["Sets the color and transparency of the background of the timers."] = "Define a cor e transparência dos fundos dos temporizadores." -- Needs review
-- L["Sets the color of the individual iconborders."] = ""
L["Sets the size of the gap between the totem icons."] = "Define o tamanho do espaço entre os ícones dos totens." -- Needs review
-- L["Sets which color the latency overlay on the castbar is using."] = ""
L["Sets which color to use on casting bar of casts that are interruptible."] = "Define qual cor usar na barra de lançamento para lançamentos interrompíves." -- Needs review
L["Sets which color to use on casting bar of casts that are not interruptible."] = "Define qual cor usar na barra de lançamento para lançamentos que não são interrompíveis." -- Needs review
L["Sets which color to use on casting bar of casts that completed."] = "Define qual cor usar na barra de lançamento para lançamentos completos." -- Needs review
-- L["Sets which color to use on casting bar of casts that failed."] = ""
-- L["Sets which color to use on casting bar of channeled casts that are interruptible."] = ""
-- L["Sets which color to use on casting bar of channeled casts that are not interruptible."] = ""
-- L["Sets which color to use on the health bar of units that have aggro."] = ""
-- L["Set the anchor point on the inside of the aura."] = ""
-- L["Set the aura filter to filter the buff auras."] = ""
-- L["Set the aura filter to filter the debuff auras."] = ""
-- L["Set the color of the border."] = ""
L["Set the color of the text."] = "Define a cor do texto." -- Needs review
L["Set the corner and side to start auras from."] = "Define o canto e lado em que as auras iniciarão." -- Needs review
-- L["Set the custom color for the highlight if not coloring by type."] = ""
-- L["Set the maximum number of buffs to display."] = ""
-- L["Set the maximum number of debuffs to display."] = ""
L["Set the number of pixels between each column of auras."] = "Define o número de pixels entre cada coluna de auras." -- Needs review
L["Set the number of pixels between each row of auras."] = "Define o número de pixels entre cada linha de auras." -- Needs review
L["Set the portrait style."] = "Define o estilo do retrato" -- Needs review
L["Set the portrait style for when the normal style can't be shown, such as if they are out of visibility."] = "Define o estilo de retrato, quando o estilo normal não puder ser exibido, como em situações de baixa visibilidade." -- Needs review
-- L["Set the type of filter."] = ""
-- L["Set when the time remaining spiral shows."] = ""
L["Set when the time remaining text shows."] = "Define quando o tempo remanescente será exibido." -- Needs review
-- L["Set when to include this filter as an option for a layout."] = ""
-- L["Shadow orbs"] = ""
L["Shaman"] = "Xamã" -- Needs review
L["Shaman can dispel"] = "Xamã pode dissipar" -- Needs review
-- L["Shaman can purge"] = ""
-- L["Shaman enemy debuffs"] = ""
L["Shaman_female"] = "Xamã" -- Needs review
-- L["Shaman friend buffs"] = ""
-- L["Shaman friend debuffs"] = ""
L["Shamans"] = "Xamãs" -- Needs review
-- L["Shaman self buffs"] = ""
-- L["Shaman_short"] = ""
-- L["Shift Right-click"] = ""
L["Short"] = "Curto"
-- L["Short level and race"] = ""
-- L["Should consolidate"] = ""
-- L["Show a bar for demonic fury for demonology warlocks."] = ""
-- L["Show a bar for the alternate power bar as used in some quests and boss encounters."] = ""
-- L["Show a bar indicating the unit's health."] = ""
L["Show a cast bar."] = "Exibe uma barra de lançamento."
L["Show a flat background for your unit frames."] = "Exibe um fundo plano para seus quadros de unidades."
-- L["Show a guessed safe zone at the end of the player castbar."] = ""
-- L["Show a highlight when hovering or targeting."] = ""
-- L["Show all"] = ""
L["Show all frames that can be shown, for easy configuration."] = "Mostrar todos os quadros que podem ser mostrados, para fácil configuração."
L["Show a mana, rage, energy, or runic power bar."] = "Exibe uma barra de mana, fúria, energia ou poder rúnico." -- Needs review
L["Show an experience bar."] = "Mostrar uma barra de experiência"
L["Show an icon based on whether or not the unit is in combat."] = "Mostra um ícone baseado se a unidade está ou não em combate."
-- L["Show an icon based on whether or not the unit's voice status."] = ""
-- L["Show an icon for the type of a battle pet."] = ""
-- L["Show an icon on the minimap to open the PitBull config."] = ""
L["Show an icon on the pet frame to indicate its happiness."] = "Exibe um ícone sobre o quadro de sua companhia para indicar que ele está feliz." -- Needs review
-- L["Show an icon on the unit frame based on which Raid Target it is."] = ""
-- L["Show an icon on the unit frame based on which Role it is."] = ""
L["Show an icon on the unit frame when the unit is in PvP mode."] = "Exibe um ícone no retrato da unidade, quando esta estiver em modo JxJ." -- Needs review
L["Show an icon on the unit frame when the unit is resting in an inn or city."] = "Exibe um ícone no retrato da unidade, quando esta estiver descansando em uma hospedagem ou cidade." -- Needs review
L["Show an icon on the unit frame when the unit is the group leader."] = "Exibe um ícone no retrato da unidade, quando esta for o líder do grupo." -- Needs review
L["Show an icon on the unit frame when the unit is the master looter."] = "Exibe um ícone no retrato da unidade, quando esta é o saqueador mestre." -- Needs review
L["Show a portrait of the unit."] = "Exibe um retrato da unidade." -- Needs review
L["Show a ready check icon on the unit frame based on their response."] = "Exibe um ícone de confirmação de \"pronto\" no retrato da unidade, baseado em sua resposta." -- Needs review
L["Show a reputation bar."] = "Exibe uma barra de reputação." -- Needs review
L["Show a threat bar."] = "Exibe uma barra de ameaça." -- Needs review
-- L["Show a tooltip on mouseover with the happiness and damage percent for the pet."] = ""
-- L["Show background on the cast bar when nothing is being cast."] = ""
L["Show combo points on the unit frame if you are a Rogue or Druid in Cat form."] = "Mostrar pontos de combo no quadro de unidade se você for um Ladino ou Druida na forma de Gato."
-- L["Show Death Knight rune icons."] = ""
-- L["Show destruction warlock burning embers."] = ""
-- L["Show Druid Eclipse Bar."] = ""
L["Show icon"] = "Ícone de exibição" -- Needs review
L["Show information like damage taken, healing taken, resists, etc. on the unit frame."] = "Mostra informações como dano recebido, cura recebida, resistencias, etc. no quadro de unidade."
-- L["Show Monk chi icons"] = ""
-- L["Show Monk chi icons."] = ""
-- L["Show overheals"] = ""
-- L["Show overheals past the end of the health bar."] = ""
-- L["Show Paladin Holy power icons."] = ""
-- L["Show Priest shadow orbs."] = ""
-- L["Show Priest Shadow orbs."] = ""
-- L["Shows buffs and debuffs for PitBull4 frames."] = ""
-- L["Shows the pie-like cooldown spiral on the icons."] = ""
L["Shows the remaining time in as text."] = "Exibe o tempo remanescente como texto." -- Needs review
L["Show the combo points stacked vertically instead of horizontally."] = "Mostra os pontos de combo acumulados verticalmente ao invés de horizontalmente."
L["Show the full body of the unit when in 3D mode."] = "Exibe o corpo inteiro da unidade, quando em modo 3D" -- Needs review
-- L["Show the icons stacked vertically instead of horizontally."] = ""
L["Show the mana bar when a druid is in cat or bear form or a mistweaver monk is in stance of the fierce tiger."] = "Exibe a barra de mana, quando um Druida está em forma de urso ou de felino." -- Needs review
L["Show the owner instead of the vehicle."] = "Exibe o proprietário, em vez do veículo." -- Needs review
-- L["Show the runes stacked vertically instead of horizontally."] = ""
L["Show the spellcasting five-second rule."] = "Exibe a regra dos \"cinco segundos\" para evocação de magia." -- Needs review
-- L["Show the tooltip for the unit when the mouse is over the frame under the selected condition."] = ""
L["Show the vehicle instead of the owner."] = "Exibe o veículo, em vez do proprietário." -- Needs review
-- L["Show this raid target icon for this layout."] = ""
-- L["Show when in"] = ""
L["Show which Totems are dropped and the time left until they expire."] = "Exibe quais totens foram lançados e o tempo até que eles expirem." -- Needs review
L["Side"] = "Lado" -- Needs review
-- L["Simple"] = ""
L["'%s' is already a text."] = "'%s' já é um texto." -- Needs review
L["Size"] = "Tamanho" -- Needs review
-- L["Size auras to use up as much of the space available as possible."] = ""
L["Size of the indicator."] = "Tamanho do indicador." -- Needs review
L["Size of the text."] = "Tamanho do texto." -- Needs review
L["Size of the unit frame."] = "Tamanho do quadro da unidade." -- Needs review
-- L["Size to fit"] = ""
L["Smart"] = "Esperto"
L["Smooth opacity change"] = "Mudança de opacidade suavizada" -- Needs review
L["Solo"] = "Sozinho" -- Needs review
L["Some codes provided for you."] = "Alguns códigos fornecidos para você."
L["Sort"] = "Ordenação" -- Needs review
-- L["Sort auras by type and alphabetically, preferring your own auras first."] = ""
L["Sort direction"] = "Direção de ordenação" -- Needs review
L["Sort method"] = "Método de ordenação" -- Needs review
L["Sounds"] = "Sons" -- Needs review
L["Spacing"] = "Espaçamento" -- Needs review
L["Spacing between adjacent indicators."] = "Espaçamento entre indicadores adjacentes." -- Needs review
L["Spacing in pixels between bars."] = "Espaçamento em pixels entre as barras." -- Needs review
-- L["Spell id"] = ""
-- L["Spiral Timer"] = ""
-- L["%s|r to open the options menu"] = ""
-- L["%s|r to toggle frame lock"] = ""
-- L["%s|r to toggle frame snapping"] = ""
L["%s's pet"] = "%s da companhia" -- Needs review
L["%s's %s"] = "%s da %s" -- Needs review
L["%s's target"] = "Alvo de %s" -- Needs review
L["Standalone config"] = "Configuração autônoma" -- Needs review
L["Standard"] = "Padrão"
L["Standard name"] = "Nome padrão"
L["Standard time"] = "Horário padrão" -- Needs review
L["%s target"] = "Alvo de %s" -- Needs review
L["%s targets"] = "Alvos de %s" -- Needs review
-- L["Start a new column whenever the size of the aura changes."] = ""
-- L["Start a new row whenever the size of the aura changes."] = ""
L["Start at"] = "Inicia em" -- Needs review
L["Status bars graphically display a value from 0% to 100%."] = "Barra de status mostra graficamente um valor entre 0% e 100%."
-- L["Stealable"] = ""
-- L["Strata"] = ""
L["Style"] = "Estilo" -- Needs review
-- L["Suppress Cooldown Counts"] = ""
L["Swap with owner"] = "Troca com o proprietário" -- Needs review
L["Swap with vehicle"] = "Troca com o veículo" -- Needs review
L["Tapped"] = "Perfurado" -- Needs review
L["Target"] = "Alvo"
L["Target-selected opacity"] = "Opacidade de Alvo Selecionado" -- Needs review
-- L["Taruen enemy debuffs"] = ""
L["Tauren"] = "Tauren" -- Needs review
L["Tauren_female"] = "Taurina" -- Needs review
-- L["Tauren friend buffs"] = ""
-- L["Tauren_short"] = ""
-- L["Test"] = ""
L["Text"] = "Texto" -- Needs review
L["Text provider for LibDogTag-3.0 texts."] = "Texto fornecido para os textos de LibDogTag-3.0." -- Needs review
-- L["Text provider using Lua scripts to generate texts."] = ""
L["Texts"] = "Textos"
L["Texts convey information in a non-graphical manner."] = "Textos mostram a informação de uma maneira não gráfica." -- Needs review
L["Text Timer"] = "Temporizador de texto" -- Needs review
L["Texture"] = "Textura" -- Needs review
-- L["The background color behind the icons."] = ""
-- L["The background color behind the runes."] = ""
-- L["The color of the active icons."] = ""
L["The color of the bar that shows incoming heals from other players."] = "A cor da barra que exibe as curas vindas de outros jogadores." -- Needs review
L["The color of the bar that shows your own heals, when full overhealing is due."] = "A cor da barra que exibe suas próprias curas, quando uma total cura excedente ocorre." -- Needs review
L["The color of the bar that shows your own heals, when no overhealing is due."] = "A cor da barra que exibie suas próprias curas, quando não ocorre cura excedente." -- Needs review
-- L["The color of the inactive icons."] = ""
L["The False filter is always false."] = "O filtro \"Falso\" é sempre falso." -- Needs review
L["The font of texts, unless overridden."] = "A fonte dos textos, a menos que ultrapassada." -- Needs review
L["The maximum amount of units per column before making a new column."] = "Quantidade máxima de unidades por coluna, antes que uma nova coluna seja criada." -- Needs review
L["The maximum amount of units per row before making a new row."] = "Quantidade máxima de unidades por linha, antes que uma nova linha seja criada." -- Needs review
L["The maximum opacity that a shown frame can be."] = "A opacidade máxima que um quadro visível pode ter." -- Needs review
L["The minimum opacity that a shown frame can be."] = "A opacidade mínima que um quadro visível pode ter." -- Needs review
L["The opacity to display if the player is in combat."] = "Opacidade a ser exibida se o jogador está em combate."
L["The opacity to display if the player is missing health or mana."] = "A opacidade a ser exibida se o jogador está sem vida ou mana."
L["The opacity to display if the player is out of combat."] = "A opacidade para exibir se o jogador está fora de combate." -- Needs review
L["The opacity to display if the player is out of range of the unit."] = "A opacidade para demonstrar que o jogador está fora do campo de visão da unidade." -- Needs review
L["The opacity to display if the player is selecting a target."] = "A opacidade a ser exibida se o jogador está selecionando um alvo."
L["The opacity to display if the unit is friendly."] = "A opacidade para exibir se a unidade é amigável." -- Needs review
L["The opacity to display if the unit is hostile."] = "A opacidade para exibir se a unidade é hostil." -- Needs review
L["The order in which the elements appear."] = "A ordem na qual os elementos aparecem." -- Needs review
L["There are more options for this module in the Layout editor -> Indicators -> Totems section."] = "Há mais opções para este módulo no Editor de Leiaute -> Indicadores -> Seção de totens." -- Needs review
L["There are more options for this module in the Modules -> Totems section."] = "Há mais opções para este módulo em Módulos -> seção Totens." -- Needs review
L["The scale of the unit. This will be multiplied against the layout's scale."] = "A escala da unidade. Será multiplicado pela escala do leiaute." -- Needs review
L["These color definitions will be used by per-element settings that need seperate color info per element."] = "Estas definições de cor serão utilizadas pelas configurações de cada elemento, que necessitem de informação de cor por elemento." -- Needs review
L["The texture of status bars, unless overridden."] = "A textura da barra de status, a menos que sobrescrita." -- Needs review
L["The True filter is always true."] = "O filtro \"Verdadeiro\" é sempre verdadeiro." -- Needs review
L["Thin Border"] = "Borda fina" -- Needs review
-- L["This assumes spells cannot be (locally) triggered before the GCD has run out."] = ""
-- L["This module can not be loaded: %s"] = ""
L["This plays a sound file when a totem expires or gets destroyed. Individual sounds can be set per element."] = "Executa um arquivo de áudio, quando o totem expira ou é destruído. Sons individuais podem ser definidos para cada elemento." -- Needs review
-- L["This will make a new bar for this layout."] = ""
L["This will make a new text for the layout."] = "Isto criará um novo texto para o leiaute." -- Needs review
L["Threat"] = "Ameaça" -- Needs review
L["Threat bar"] = "Barra de ameaça" -- Needs review
-- L["Time in seconds that the animation and/or fade takes to play."] = ""
L["Time Left"] = "Tempo restante" -- Needs review
-- L["Time remaining spiral"] = ""
L["Time remaining text"] = "Tempo do texto remanescente." -- Needs review
L["Time unit"] = "Unidade de tempo" -- Needs review
L["Tooltip"] = "Dicas" -- Needs review
L["Top"] = "Topo"
-- L["Top, Inside"] = ""
L["Top-left"] = "Esquerda no topo" -- Needs review
-- L["Top-left on left"] = ""
-- L["Top-left on top"] = ""
-- L["Top, Outside"] = ""
L["Top-right"] = "Direita no topo" -- Needs review
-- L["Top-right on right"] = ""
-- L["Top-right on top"] = ""
L["Totem Direction"] = "Direção do Totem" -- Needs review
L["Totems"] = "Totens" -- Needs review
L["Totems only show for the Player. On all other units the frame will not be there, even when enabled in the layout of the frame."] = "Totens exibidos apenas para o jogador. Para todas as outras unidades o quadro não estará lá, mesmo quando habilitado no leiaute do quadro." -- Needs review
L["Totemsounds"] = "Som dos totens" -- Needs review
L["Totem Spacing"] = "Espaçamento dos totens." -- Needs review
L["Totems per line"] = "Totens por linha" -- Needs review
L["Totem Tooltips"] = "Dicas de totem" -- Needs review
-- L["Trade (~11 yards)"] = ""
L["Travel"] = "Viagem" -- Needs review
L["Tree"] = "Árvore" -- Needs review
-- L["Tries to suppress CooldownCount-like addons on the spiral timer. (Requires UI reload to change the setting!)"] = ""
L["Troll"] = "Troll" -- Needs review
L["Troll_female"] = "Trollesa" -- Needs review
-- L["Troll friend buffs"] = ""
-- L["Troll self buffs"] = ""
-- L["Troll_short"] = ""
L["True"] = "Verdadeiro" -- Needs review
L["Type"] = "Tipo" -- Needs review
-- L["Type of test to check the caster by."] = ""
-- L["Type of test to check the unit by."] = ""
-- L["Types of the auras you want the filter to include or exclude."] = ""
-- L["Type %s to Clear Focus"] = ""
-- L["Type %s to Set Focus"] = ""
-- L["Undead"] = ""
L["Undead_female"] = "Renegada" -- Needs review
-- L["Undead friend buffs"] = ""
-- L["Undead self buffs"] = ""
-- L["Undead_short"] = ""
L["Uninterruptible"] = "Ininterrompível" -- Needs review
L["Unit"] = "Unidade" -- Needs review
L["Unit formation"] = "Formation de unidade" -- Needs review
L["Unit frame"] = "Painel da unidade" -- Needs review
L["Unit group"] = "Unidade de grupo" -- Needs review
-- L["Unit pass in arg1 of event"] = ""
L["Units"] = "Unidades" -- Needs review
L["Units per column"] = "Unidades por coluna" -- Needs review
L["Units per row"] = "Unidades por linha" -- Needs review
L["Unknown Slot "] = "Posição desconhecida" -- Needs review
-- L["Unlocked without snap"] = ""
-- L["Unlocked with snap"] = ""
L["<Unnamed>"] = "<Sem nome>" -- Needs review
L["Unscaled size of indicators."] = "Tamanho não redimensionado dos indicadores." -- Needs review
L["Update for"] = "Atualização para" -- Needs review
-- L["Up then left"] = ""
-- L["Up then right"] = ""
L["Use spell icon"] = "Icone de magia." -- Needs review
-- L["Use the auras type to select the color of the highlight."] = ""
L["Use the spell icon for the weapon enchant rather than the icon for the weapon."] = "Usa o ícone de magia para armas encantadas, em vez do ícone usado para armas." -- Needs review
L["Value"] = "Valor" -- Needs review
L["Value needs to be a number."] = "O valor deve ser um número." -- Needs review
L["Vehicle"] = "Veículo" -- Needs review
L["Version: %s"] = "Versão: %s" -- Needs review
L["Vertical"] = "Vertical"
L["Vertical offset"] = "Deslocamento vertical" -- Needs review
L["Vertical position"] = "Posição vertical" -- Needs review
L["Vertical position on the y-axis of the screen."] = "Posição vertical no eixo \"y\" da tela." -- Needs review
L["Vertical spacing"] = "Espaçamento vertical" -- Needs review
-- L["Visible (~100 yards)"] = ""
L["Visual heal"] = "Cura visual" -- Needs review
L["Visualises healing done by you and your group members before it happens."] = "Visualiza curas realizadas por você e pelos membros de seu grupo, antes que elas aconteçam." -- Needs review
L["Voice icon"] = "Ícone de voz" -- Needs review
L["Warlock"] = "Bruxo" -- Needs review
L["Warlock can dispel"] = "Bruxo pode dissipar" -- Needs review
-- L["Warlock can purge"] = ""
-- L["Warlock enemy debuffs"] = ""
L["Warlock_female"] = "Bruxa" -- Needs review
-- L["Warlock friend buffs"] = ""
-- L["Warlock pet buffs"] = ""
L["Warlocks"] = "Bruxos" -- Needs review
-- L["Warlock self buffs"] = ""
-- L["Warlock_short"] = ""
L["Warrior"] = "Guerreiro" -- Needs review
L["Warrior can dispel"] = "Guerreiro pode dissipar" -- Needs review
-- L["Warrior can purge"] = ""
-- L["Warrior enemy debuffs"] = ""
L["Warrior_female"] = "Guerreira" -- Needs review
-- L["Warrior friend buffs"] = ""
L["Warriors"] = "Guerreiros" -- Needs review
-- L["Warrior self buffs"] = ""
-- L["Warrior self debuffs"] = ""
-- L["Warrior_short"] = ""
L["Water"] = "Água" -- Needs review
L["Weapon enchant"] = "Encantamento de arma" -- Needs review
L["Weapon Enchant"] = "Encantamento de arma" -- Needs review
-- L["Weapon enchants"] = ""
L["Weapon enchants count"] = "Contador de encantamento de armas" -- Needs review
-- L["Weapon enchants time remaining"] = ""
-- L["Weapon quality"] = ""
-- L["What background color to override the bar with."] = ""
-- L["What color should be applied to the border if it is a boss unit."] = ""
L["What color should be applied to the border if it is an elite unit."] = "Qual cor deverá ser aplicada à borda, se é uma unidade de elite." -- Needs review
L["What color should be applied to the border if it is a normal unit."] = "Qual cor deverá ser aplicada à borda, se é uma unidade normal." -- Needs review
L["What color should be applied to the border if it is a rare unit."] = "Qual cor deverá ser aplicada à borda, se a unidade é rara." -- Needs review
-- L["What color the combo points should be."] = ""
-- L["What color to override the bar with."] = ""
L["What location to position the timer text at."] = "Qual local posicionar o texto de tempo." -- Needs review
-- L["What rested color to override the bar with."] = ""
-- L["What side of the bar to show the icon on."] = ""
L["What text provider is used for this text."] = "Qual provedor de texto é usado para este texto." -- Needs review
-- L["What texture should be applied to the border if it is a boss unit."] = ""
L["What texture should be applied to the border if it is an elite unit."] = "Qual textura deverá ser aplicada à borda, se a unidade é de elite." -- Needs review
L["What texture should be applied to the border if it is a normal unit."] = "Qual textura deverá ser aplicada à borda, se é uma unidade normal." -- Needs review
L["What texture should be applied to the border if it is a rare unit."] = "Qual textura deverá ser aplicada à borda, se a unidade é rara." -- Needs review
-- L["What texture the highlight should use."] = ""
L["What texture the status bar should use."] = "Qual textura a barra de status deve usar." -- Needs review
-- L["What texture to use for combo points."] = ""
-- L["What to map based on."] = ""
-- L["When targetted"] = ""
L["Where on the control to place the indicator."] = "Em qual lugar do controle para colocar o indicador." -- Needs review
L["Where on the control to place the text."] = "Onde colocar este texto no controle." -- Needs review
L["Where to place the bar in relation to other bars on the frame."] = "Onde posicionar a barra em relação a outras barras no painel." -- Needs review
L["Where to place the indicator compared to others in the same location."] = "Onde colocar o indicador comparado a outros na mesma localização." -- Needs review
L["Where to place the text compared to others in the same location."] = "Onde colocar o texto, em comparação aos outros da mesma localização." -- Needs review
L["Whether all options will be mirrored, e.g. what would be on the bottom is now on the top and vice-versa."] = "Se todas as opções serão espelhadas, ex. o que estaria na base está no topo agora e vice-versa." -- Needs review
L["Whether all options will be mirrored, e.g. what would be on the left is now on the right and vice-versa."] = "Se todas as opções serão espelhadas, ex. o que estaria na esquerda está na direita agora e vice-versa." -- Needs review
-- L["Whether the unit should be unclickable, allowing you to use it as a HUD without interfering with the game world."] = ""
-- L["Whether to override the background color and use a custom one."] = ""
-- L["Whether to override the color and use a custom one."] = ""
-- L["Whether to override the rested color and use a custom one."] = ""
-- L["Whether to position as a bar rather than a floating indicator."] = ""
-- L["Whether to show the icon that is being cast."] = ""
L["Which control to attach to."] = "Em qual controle fixar." -- Needs review
L["Which direction to sort the frames within a group."] = "Em qual direção ordenar os retratos dentro do grupo." -- Needs review
-- L["Which font to use for this indicator."] = ""
L["Which font to use for this text."] = "Qual fonte usar para este texto." -- Needs review
L["Which layout the unit should use. Note: Use the layout editor to change any layout settings."] = "Qual leiaute a unidade deve usar. Observe: Use o editor de leiaute para alterar qualquer configuração de leiaute." -- Needs review
L["Which side of the unit frame to place the status bar on. Note: For the left and right sides, your bar will be vertical rather than horizontal."] = "Em qual lado do painel da unidade para colocar a barra de status. Para o lado esquerdo e direito sua barra será vertical no lugar de horizontal." -- Needs review
L["Which situations to show the unit group in."] = "Em quais situações exibir a unidade do grupo." -- Needs review
L["Which units this group should show."] = "Quais unidades este grupo deverá exibir." -- Needs review
L["Which way frames should placed."] = "Em qual direção os retratos serão colocados." -- Needs review
-- L["Whitelist"] = ""
L["Width"] = "Largura" -- Needs review
L["Width multiplier"] = "Multiplicador da largura" -- Needs review
L["Width of the unit frame."] = "Largura do quadro da unidade." -- Needs review
L["Width type"] = "Tipo de largura" -- Needs review
-- L["Worgen"] = ""
-- L["Worgen_female"] = ""
-- L["Worgen friend buffs"] = ""
-- L["Worgen self buffs"] = ""
-- L["Worgen_short"] = ""
-- L["Yes"] = ""
-- L["You do not appear to have any addon installed that uses LibSharedMedia. If you want to select which sounds are used it is recommended that you install at least the 'SharedMedia' addon. (Don't install the 'LibSharedMedia' library yourself.)"] = ""
L["You have no enabled text providers."] = "Você não habilitou provedores de texto." -- Needs review
L["Zoom icon"] = "Ícone de zoom" -- Needs review
-- L["Zoom in on aura icons slightly."] = ""

--@end-non-debug@
