local L = LibStub("AceLocale-3.0"):GetLocale("SunnArt", true)

SunnArt_DEFAULTS = {
	global = {
		themes = {
			["SunnArt\\forsaken"] = "Forsaken",
			["SunnArt\\tribal"] = "Tribal",
			["SunnArt\\royal"] = "Royal",
			["SunnArt\\rogue"] = "Rogue",
			["solid"] = L["Solid colour"],
		},
		overlaps = {
		},
		lengths = {
		},
		panels = {
		},
	},
	profile = {
		artwork = true,
		framestrata = "1-BACKGROUND",
		bar = {
			[1] = {
				enabled = true,
				size = 15.6,
				alpha = 1,
				resize = false,
				scale = 1,
				rotate = false,
				flip = false,
				fit = false,
				autostretch = true,
				theme = "SunnArt\\royal",
				panels = 3,
				overlap = 0,
				length = 0,
				red = 0,
				green = 0,
				blue = 0,
			},
			[2] = {
				enabled = true,
				size = 1.9,
				alpha = 1,
				resize = false,
				scale = 1,
				rotate = true,
				flip = false,
				fit = false,
				autostretch = true,
				theme = "SunnArt\\royal",
				panels = 3,
				overlap = 0,
				length = 0,
				red = 0,
				green = 0,
				blue = 0,
			},
			[3] = {
				enabled = false,
				size = 2,
				alpha = 1,
				resize = false,
				scale = 1,
				rotate = false,
				flip = false,
				fit = true,
				autostretch = true,
				theme = "SunnArt\\royal",
				panels = 3,
				overlap = 0,
				length = 0,
				red = 0,
				green = 0,
				blue = 0,
			},
			[4] = {
				enabled = false,
				size = 2,
				alpha = 1,
				resize = false,
				scale = 1,
				rotate = false,
				flip = false,
				fit = true,
				autostretch = true,
				theme = "SunnArt\\royal",
				panels = 3,
				overlap = 0,
				length = 0,
				red = 0,
				green = 0,
				blue = 0,
			},
		},
	},
}
