SunnArt.options.args.theme.values["SunnArtPack6\\nutribe"]="Nutribe"
SunnArt.overlap["SunnArtPack6\\nutribe"]=13.67
SunnArt.options.args.theme.values["SunnArtPack6\\frostspire"]="Frost Spire"
SunnArt.overlap["SunnArtPack6\\frostspire"]=52.73
SunnArt.options.args.theme.values["SunnArtPack6\\streamred"]="StreamRed"
SunnArt.overlap["SunnArtPack6\\streamred"]=58.39
SunnArt.options.args.theme.values["SunnArtPack6\\streamblue"]="StreamBlue"
SunnArt.overlap["SunnArtPack6\\streamblue"]=53.71
SunnArt.options.args.theme.values["SunnArtPack6\\finwe"]="Finwe"
SunnArt.options.args.theme.values["SunnArtPack6\\fractal"]="Fractal"
SunnArt.overlap["SunnArtPack6\\fractal"]=50