--
-- Proculas: Enchant Procs
-- Created by Mcstabin of Hellscream [US]
--
-- Generated by Proc DB 3.0
--

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local EnchantProcs = Proculas:NewModule("EnchantProcs")
if not Proculas.enabled then
	return nil
end

local PROCS = {
	[4083] = {spellIds={"74221"},types={"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},onSelfOnly=0,procId="10"}, -- Proc #10: Hurricane
	[4084] = {spellIds={"74224"},types={"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},onSelfOnly=0,procId="37"}, -- Proc #37: Heartsong
	[4067] = {spellIds={"74196"},types={"SPELL_DAMAGE"},onSelfOnly=0,procId="40"}, -- Proc #40: Avalanche
}

function EnchantProcs:OnInitialize()
	Proculas:addProcList('ENCHANTS',PROCS)
end