--
-- Proculas: Mage Procs
-- Created by Mcstabin of Hellscream [US]
--
-- Generated by Proc DB 3.0
--

if select(2, UnitClass("player")) ~= "MAGE" then return end

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local MageProcs = Proculas:NewModule("MageProcs")
if not Proculas.enabled then
	return nil
end

local PROCS = {

}

function MageProcs:OnInitialize()
	Proculas:addProcList('MAGE',PROCS)
end
