--
-- Proculas: Paladin Procs
-- Created by Mcstabin of Hellscream [US]
--
-- Generated by Proc DB 3.0
--

if select(2, UnitClass("player")) ~= "PALADIN" then return end

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local PaladinProcs = Proculas:NewModule("PaladinProcs")
if not Proculas.enabled then
	return nil
end

local PROCS = {

}

function PaladinProcs:OnInitialize()
	Proculas:addProcList('PALADIN',PROCS)
end