--
-- Proculas: Rogue Procs
-- Created by Mcstabin of Hellscream [US]
--
-- Generated by Proc DB 3.0
--

if select(2, UnitClass("player")) ~= "ROGUE" then return end

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local RogueProcs = Proculas:NewModule("RogueProcs")
if not Proculas.enabled then
	return nil
end

local PROCS = {

}

function RogueProcs:OnInitialize()
	Proculas:addProcList('ROGUE',PROCS)
end